CREATE TABLE C##VAMONOSPUES.EstadoUsuario (
);

CREATE TABLE C##VAMONOSPUES.EstadoVehiculo (
);

CREATE TABLE C##VAMONOSPUES.EstadoRuta (
);

CREATE TABLE C##VAMONOSPUES.EstadoSolicitud (
);

CREATE TABLE C##VAMONOSPUES.EstadoCur (
);

CREATE TABLE C##VAMONOSPUES.TipoTransaccion (
);

CREATE TABLE C##VAMONOSPUES.MetodoPago (
);

CREATE TABLE C##VAMONOSPUES.MarcaVehiculo (
);

CREATE TABLE C##VAMONOSPUES.ModeloVehiculo (
);

CREATE TABLE C##VAMONOSPUES.ColorVehiculo (
);

CREATE TABLE C##VAMONOSPUES.Perfil (
);

CREATE TABLE C##VAMONOSPUES.Menu (
);

CREATE TABLE C##VAMONOSPUES.MenuPerfil (
);

CREATE TABLE C##VAMONOSPUES.Usuario (
);

CREATE TABLE C##VAMONOSPUES.VerificacionCorreo (
);

CREATE TABLE C##VAMONOSPUES.UsuarioPerfil (
);

CREATE TABLE C##VAMONOSPUES.Device (
);

CREATE TABLE C##VAMONOSPUES.Ruta (
);

CREATE TABLE C##VAMONOSPUES.PuntoEncuentro (
);

CREATE TABLE C##VAMONOSPUES.SolicitudCupo (
);

CREATE TABLE C##VAMONOSPUES.CupoRuta (
);

CREATE TABLE C##VAMONOSPUES.TransaccionesCartera (
);

CREATE TABLE C##VAMONOSPUES.HistorialViaje (
);

CREATE TABLE C##VAMONOSPUES.Calificacion (
);

