-- Script para asignar perfiles (USUARIO_PERFIL) a usuarios existentes

-- Verificar que los usuarios existan
SELECT DOCUMENTO_USU, NOMBRES_USU FROM USUARIO 
WHERE DOCUMENTO_USU IN ('1234567890', '0987654321', '1122334455');

-- Asignar perfiles
INSERT INTO USUARIO_PERFIL (DOCUMENTO_USU_UPE, ID_PER_UPE, CALIFICACION_UPE, FECHA_UPE)
VALUES ('1234567890', 1, 4.5, SYSDATE);  -- Davison -> PASAJERO

INSERT INTO USUARIO_PERFIL (DOCUMENTO_USU_UPE, ID_PER_UPE, CALIFICACION_UPE, FECHA_UPE)
VALUES ('0987654321', 2, 4.8, SYSDATE);  -- Jose Luis -> CONDUCTOR

INSERT INTO USUARIO_PERFIL (DOCUMENTO_USU_UPE, ID_PER_UPE, CALIFICACION_UPE, FECHA_UPE)
VALUES ('1122334455', 3, 5.0, SYSDATE);  -- Emmanuel -> ADMIN

COMMIT;

-- Verificar que los perfiles fueron asignados
SELECT u.DOCUMENTO_USU, u.NOMBRES_USU, p.NOMBRE_PER, up.CALIFICACION_UPE 
FROM USUARIO u
JOIN USUARIO_PERFIL up ON u.DOCUMENTO_USU = up.DOCUMENTO_USU_UPE
JOIN PERFIL p ON up.ID_PER_UPE = p.ID_PER
WHERE u.DOCUMENTO_USU IN ('1234567890', '0987654321', '1122334455');
