
-- ============================================================
-- SECCIÓN 9: DATOS INICIALES (CATÁLOGOS)
-- ============================================================

-- ESTADO_USUARIO
INSERT INTO ESTADO_USUARIO VALUES (SEQ_ESTADO_USUARIO.NEXTVAL, 'ACTIVO',     'Usuario activo en el sistema');
INSERT INTO ESTADO_USUARIO VALUES (SEQ_ESTADO_USUARIO.NEXTVAL, 'INACTIVO',   'Usuario inactivo temporalmente');
INSERT INTO ESTADO_USUARIO VALUES (SEQ_ESTADO_USUARIO.NEXTVAL, 'SUSPENDIDO', 'Usuario suspendido por incumplimiento');
INSERT INTO ESTADO_USUARIO VALUES (SEQ_ESTADO_USUARIO.NEXTVAL, 'BANEADO',    'Usuario baneado permanentemente');

-- ESTADO_VEHICULO
INSERT INTO ESTADO_VEHICULO VALUES (SEQ_ESTADO_VEHICULO.NEXTVAL, 'ACTIVO',      'Vehiculo habilitado para rutas');
INSERT INTO ESTADO_VEHICULO VALUES (SEQ_ESTADO_VEHICULO.NEXTVAL, 'INACTIVO',    'Vehiculo deshabilitado');
INSERT INTO ESTADO_VEHICULO VALUES (SEQ_ESTADO_VEHICULO.NEXTVAL, 'EN_REVISION', 'Vehiculo en proceso de verificacion');

-- ESTADO_RUTA
INSERT INTO ESTADO_RUTA VALUES (SEQ_ESTADO_RUTA.NEXTVAL, 'PROGRAMADA', 'Ruta creada y disponible para solicitudes');
INSERT INTO ESTADO_RUTA VALUES (SEQ_ESTADO_RUTA.NEXTVAL, 'EN_CURSO',   'Ruta en progreso');
INSERT INTO ESTADO_RUTA VALUES (SEQ_ESTADO_RUTA.NEXTVAL, 'COMPLETADA', 'Ruta finalizada exitosamente');
INSERT INTO ESTADO_RUTA VALUES (SEQ_ESTADO_RUTA.NEXTVAL, 'CANCELADA',  'Ruta cancelada por el conductor');

-- ESTADO_SOLICITUD
INSERT INTO ESTADO_SOLICITUD VALUES (SEQ_ESTADO_SOLICITUD.NEXTVAL, 'PENDIENTE',  'Solicitud en espera de aprobacion');
INSERT INTO ESTADO_SOLICITUD VALUES (SEQ_ESTADO_SOLICITUD.NEXTVAL, 'APROBADA',   'Solicitud aceptada por el conductor');
INSERT INTO ESTADO_SOLICITUD VALUES (SEQ_ESTADO_SOLICITUD.NEXTVAL, 'RECHAZADA',  'Solicitud rechazada por el conductor');
INSERT INTO ESTADO_SOLICITUD VALUES (SEQ_ESTADO_SOLICITUD.NEXTVAL, 'CANCELADA',  'Solicitud cancelada por el pasajero');

-- ESTADO_CUR
INSERT INTO ESTADO_CUR VALUES (SEQ_ESTADO_CUR.NEXTVAL, 'ACTIVO',     'Cupo activo en la ruta');
INSERT INTO ESTADO_CUR VALUES (SEQ_ESTADO_CUR.NEXTVAL, 'COMPLETADO', 'Cupo completado exitosamente');
INSERT INTO ESTADO_CUR VALUES (SEQ_ESTADO_CUR.NEXTVAL, 'CANCELADO',  'Cupo cancelado');

-- TIPO_TRANSACCION
INSERT INTO TIPO_TRANSACCION VALUES (SEQ_TIPO_TRANSACCION.NEXTVAL, 'DEPOSITO',  'Recarga de saldo en cartera');
INSERT INTO TIPO_TRANSACCION VALUES (SEQ_TIPO_TRANSACCION.NEXTVAL, 'RETIRO',    'Retiro de saldo de cartera');
INSERT INTO TIPO_TRANSACCION VALUES (SEQ_TIPO_TRANSACCION.NEXTVAL, 'PAGO',      'Pago de cupo de ruta');
INSERT INTO TIPO_TRANSACCION VALUES (SEQ_TIPO_TRANSACCION.NEXTVAL, 'REEMBOLSO', 'Devolucion por cancelacion');

-- METODO_PAGO
INSERT INTO METODO_PAGO VALUES (SEQ_METODO_PAGO.NEXTVAL, 'CARTERA_VIRTUAL');
INSERT INTO METODO_PAGO VALUES (SEQ_METODO_PAGO.NEXTVAL, 'EFECTIVO');
INSERT INTO METODO_PAGO VALUES (SEQ_METODO_PAGO.NEXTVAL, 'TARJETA_CREDITO');
INSERT INTO METODO_PAGO VALUES (SEQ_METODO_PAGO.NEXTVAL, 'TARJETA_DEBITO');

-- PERFIL
INSERT INTO PERFIL VALUES (SEQ_PERFIL.NEXTVAL, 'PASAJERO',  'Usuario que solicita cupos de ruta',       SYSDATE);
INSERT INTO PERFIL VALUES (SEQ_PERFIL.NEXTVAL, 'CONDUCTOR', 'Usuario que ofrece rutas con vehiculo',    SYSDATE);
INSERT INTO PERFIL VALUES (SEQ_PERFIL.NEXTVAL, 'ADMIN',     'Administrador del sistema',                SYSDATE);

-- MARCA_VEHICULO (muestra)
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'CHEVROLET');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'RENAULT');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'TOYOTA');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'MAZDA');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'KIA');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'NISSAN');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'VOLKSWAGEN');

-- COLOR_VEHICULO (muestra)
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'BLANCO');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'NEGRO');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'GRIS');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'ROJO');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'AZUL');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'VERDE');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'PLATEADO');

COMMIT;