-- CreateTable
CREATE TABLE "ESTADO_USUARIO" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "descripcion" TEXT
);

-- CreateTable
CREATE TABLE "ESTADO_VEHICULO" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "descripcion" TEXT
);

-- CreateTable
CREATE TABLE "ESTADO_RUTA" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "descripcion" TEXT
);

-- CreateTable
CREATE TABLE "ESTADO_SOLICITUD" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "descripcion" TEXT
);

-- CreateTable
CREATE TABLE "ESTADO_CUR" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "descripcion" TEXT
);

-- CreateTable
CREATE TABLE "TIPO_TRANSACCION" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "descripcion" TEXT
);

-- CreateTable
CREATE TABLE "METODO_PAGO" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "MARCA_VEHICULO" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "MODELO_VEHICULO" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "anio" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "COLOR_VEHICULO" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "PERFIL" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "descripcion" TEXT,
    "fechaCreacion" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "MENU" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "url" TEXT NOT NULL,
    "nombre" TEXT NOT NULL,
    "idPadre" INTEGER,
    "orden" INTEGER NOT NULL,
    CONSTRAINT "MENU_idPadre_fkey" FOREIGN KEY ("idPadre") REFERENCES "MENU" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "MENU_PERFIL" (
    "idMenu" INTEGER NOT NULL,
    "idPerfil" INTEGER NOT NULL,
    "insertar" TEXT NOT NULL,
    "actualizar" TEXT NOT NULL,
    "eliminar" TEXT NOT NULL,
    "consultar" TEXT NOT NULL,

    PRIMARY KEY ("idMenu", "idPerfil"),
    CONSTRAINT "MENU_PERFIL_idMenu_fkey" FOREIGN KEY ("idMenu") REFERENCES "MENU" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "MENU_PERFIL_idPerfil_fkey" FOREIGN KEY ("idPerfil") REFERENCES "PERFIL" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "USUARIO" (
    "documentoUsu" TEXT NOT NULL PRIMARY KEY,
    "nombresUsu" TEXT NOT NULL,
    "primerApellidoUsu" TEXT NOT NULL,
    "segundoApellidoUsu" TEXT,
    "correoUsu" TEXT NOT NULL,
    "numeroTelefonoUsu" TEXT NOT NULL,
    "fechaNacimientoUsu" DATETIME NOT NULL,
    "contrasenaUsu" TEXT NOT NULL,
    "fotoUrlUsu" TEXT NOT NULL,
    "saldoCarteraUsu" BIGINT NOT NULL DEFAULT 0,
    "fechaCreacionUsu" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAtUsu" DATETIME NOT NULL,
    "idEstUsu" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "USUARIO_idEstUsu_fkey" FOREIGN KEY ("idEstUsu") REFERENCES "ESTADO_USUARIO" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "VERIFICACION_CORREO" (
    "idVer" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "documentoUsuVer" TEXT NOT NULL,
    "codigoVer" TEXT NOT NULL,
    "fechaExpiracionVer" DATETIME NOT NULL,
    "usadoVer" TEXT NOT NULL DEFAULT 'N',
    "fechaCreacionVer" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "VERIFICACION_CORREO_documentoUsuVer_fkey" FOREIGN KEY ("documentoUsuVer") REFERENCES "USUARIO" ("documentoUsu") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "USUARIO_PERFIL" (
    "idUsp" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "documentoUsuUsp" TEXT NOT NULL,
    "idPerUsp" INTEGER NOT NULL,
    "calificacionUsu" BIGINT NOT NULL DEFAULT 500,
    "fechaAsignacionUsp" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "USUARIO_PERFIL_documentoUsuUsp_fkey" FOREIGN KEY ("documentoUsuUsp") REFERENCES "USUARIO" ("documentoUsu") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "USUARIO_PERFIL_idPerUsp_fkey" FOREIGN KEY ("idPerUsp") REFERENCES "PERFIL" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "VEHICULO" (
    "idVeh" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "placaVeh" TEXT NOT NULL,
    "documentoUsuVeh" TEXT NOT NULL,
    "idMarVeh" INTEGER NOT NULL,
    "idModVeh" INTEGER NOT NULL,
    "idColVeh" INTEGER NOT NULL,
    "idEstVeh" INTEGER NOT NULL,
    "licenciaUrlVeh" TEXT NOT NULL,
    "vehiculoUrlVeh" TEXT NOT NULL,
    "licTransitoUrlVeh" TEXT NOT NULL,
    "soatUrlVeh" TEXT NOT NULL,
    "fechaRegistroVeh" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAtVeh" DATETIME NOT NULL,
    CONSTRAINT "VEHICULO_documentoUsuVeh_fkey" FOREIGN KEY ("documentoUsuVeh") REFERENCES "USUARIO" ("documentoUsu") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "VEHICULO_idMarVeh_fkey" FOREIGN KEY ("idMarVeh") REFERENCES "MARCA_VEHICULO" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "VEHICULO_idModVeh_fkey" FOREIGN KEY ("idModVeh") REFERENCES "MODELO_VEHICULO" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "VEHICULO_idColVeh_fkey" FOREIGN KEY ("idColVeh") REFERENCES "COLOR_VEHICULO" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "VEHICULO_idEstVeh_fkey" FOREIGN KEY ("idEstVeh") REFERENCES "ESTADO_VEHICULO" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "RUTA" (
    "idRut" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "placaVehRut" INTEGER NOT NULL,
    "idUspRut" INTEGER NOT NULL,
    "latitudOrigenRut" BIGINT NOT NULL,
    "longitudOrigenRut" BIGINT NOT NULL,
    "latitudDestinoRut" BIGINT NOT NULL,
    "longitudDestinoRut" BIGINT NOT NULL,
    "horaSalidaRut" DATETIME NOT NULL,
    "cuposTotalesRut" INTEGER NOT NULL,
    "cuposDisponiblesRut" INTEGER NOT NULL,
    "precioCupoRut" BIGINT NOT NULL,
    "distanciaKmRut" BIGINT NOT NULL,
    "idEstRut" INTEGER NOT NULL,
    "fechaCreacionRut" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAtRut" DATETIME NOT NULL,
    CONSTRAINT "RUTA_placaVehRut_fkey" FOREIGN KEY ("placaVehRut") REFERENCES "VEHICULO" ("idVeh") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "RUTA_idUspRut_fkey" FOREIGN KEY ("idUspRut") REFERENCES "USUARIO_PERFIL" ("idUsp") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "RUTA_idEstRut_fkey" FOREIGN KEY ("idEstRut") REFERENCES "ESTADO_RUTA" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PUNTO_ENCUENTRO" (
    "idPun" INTEGER NOT NULL,
    "idRutPun" INTEGER NOT NULL,
    "latitudPun" BIGINT NOT NULL,
    "longitudPun" BIGINT NOT NULL,
    "ordenPun" INTEGER NOT NULL,

    PRIMARY KEY ("idPun", "idRutPun"),
    CONSTRAINT "PUNTO_ENCUENTRO_idRutPun_fkey" FOREIGN KEY ("idRutPun") REFERENCES "RUTA" ("idRut") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "SOLICITUD_CUPO" (
    "idSol" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idRutSol" INTEGER NOT NULL,
    "idUspSol" INTEGER NOT NULL,
    "idEssSol" INTEGER NOT NULL,
    "idMpaSol" INTEGER NOT NULL,
    "montoSol" BIGINT NOT NULL,
    "fechaCreacionSol" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "SOLICITUD_CUPO_idRutSol_fkey" FOREIGN KEY ("idRutSol") REFERENCES "RUTA" ("idRut") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "SOLICITUD_CUPO_idUspSol_fkey" FOREIGN KEY ("idUspSol") REFERENCES "USUARIO_PERFIL" ("idUsp") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "SOLICITUD_CUPO_idEssSol_fkey" FOREIGN KEY ("idEssSol") REFERENCES "ESTADO_SOLICITUD" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "SOLICITUD_CUPO_idMpaSol_fkey" FOREIGN KEY ("idMpaSol") REFERENCES "METODO_PAGO" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CUPO_RUTA" (
    "idSolCrp" INTEGER NOT NULL,
    "idRutCrp" INTEGER NOT NULL,
    "idCurCrp" INTEGER NOT NULL,

    PRIMARY KEY ("idSolCrp", "idRutCrp"),
    CONSTRAINT "CUPO_RUTA_idSolCrp_fkey" FOREIGN KEY ("idSolCrp") REFERENCES "SOLICITUD_CUPO" ("idSol") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CUPO_RUTA_idRutCrp_fkey" FOREIGN KEY ("idRutCrp") REFERENCES "RUTA" ("idRut") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CUPO_RUTA_idCurCrp_fkey" FOREIGN KEY ("idCurCrp") REFERENCES "ESTADO_CUR" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "TRANSACCIONES_CARTERA" (
    "idTra" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "documentoUsuTra" TEXT NOT NULL,
    "idTitTra" INTEGER NOT NULL,
    "montoTra" BIGINT NOT NULL,
    "saldoResultanteTra" BIGINT NOT NULL,
    "fechaRealizacionTra" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TRANSACCIONES_CARTERA_documentoUsuTra_fkey" FOREIGN KEY ("documentoUsuTra") REFERENCES "USUARIO" ("documentoUsu") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "TRANSACCIONES_CARTERA_idTitTra_fkey" FOREIGN KEY ("idTitTra") REFERENCES "TIPO_TRANSACCION" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "HISTORIAL_VIAJE" (
    "idHis" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "documentoUsuHis" TEXT NOT NULL,
    "idSolHis" INTEGER NOT NULL,
    "idRutHis" INTEGER NOT NULL,
    "rolViajeHis" TEXT NOT NULL,
    "costoHis" BIGINT NOT NULL,
    "fechaCreacionHis" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "HISTORIAL_VIAJE_documentoUsuHis_fkey" FOREIGN KEY ("documentoUsuHis") REFERENCES "USUARIO" ("documentoUsu") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "HISTORIAL_VIAJE_idSolHis_idRutHis_fkey" FOREIGN KEY ("idSolHis", "idRutHis") REFERENCES "CUPO_RUTA" ("idSolCrp", "idRutCrp") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CALIFICACION" (
    "idCal" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idSolCal" INTEGER NOT NULL,
    "documentoCalificadorCal" TEXT NOT NULL,
    "documentoCalificadoCal" TEXT NOT NULL,
    "rolCalificadorCal" TEXT NOT NULL,
    "puntajeCal" BIGINT NOT NULL,
    "comentarioCal" TEXT,
    "fechaCreacionCal" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "idSolCrpCal" INTEGER NOT NULL,
    "idRutCrpCal" INTEGER NOT NULL,
    "idHisCal" INTEGER NOT NULL,
    CONSTRAINT "CALIFICACION_idSolCal_fkey" FOREIGN KEY ("idSolCal") REFERENCES "SOLICITUD_CUPO" ("idSol") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "CALIFICACION_documentoCalificadorCal_fkey" FOREIGN KEY ("documentoCalificadorCal") REFERENCES "USUARIO" ("documentoUsu") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "CALIFICACION_documentoCalificadoCal_fkey" FOREIGN KEY ("documentoCalificadoCal") REFERENCES "USUARIO" ("documentoUsu") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "CALIFICACION_idSolCrpCal_idRutCrpCal_fkey" FOREIGN KEY ("idSolCrpCal", "idRutCrpCal") REFERENCES "CUPO_RUTA" ("idSolCrp", "idRutCrp") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "CALIFICACION_idHisCal_fkey" FOREIGN KEY ("idHisCal") REFERENCES "HISTORIAL_VIAJE" ("idHis") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "ESTADO_USUARIO_nombre_key" ON "ESTADO_USUARIO"("nombre");

-- CreateIndex
CREATE UNIQUE INDEX "ESTADO_VEHICULO_nombre_key" ON "ESTADO_VEHICULO"("nombre");

-- CreateIndex
CREATE UNIQUE INDEX "ESTADO_RUTA_nombre_key" ON "ESTADO_RUTA"("nombre");

-- CreateIndex
CREATE UNIQUE INDEX "ESTADO_SOLICITUD_nombre_key" ON "ESTADO_SOLICITUD"("nombre");

-- CreateIndex
CREATE UNIQUE INDEX "ESTADO_CUR_nombre_key" ON "ESTADO_CUR"("nombre");

-- CreateIndex
CREATE UNIQUE INDEX "TIPO_TRANSACCION_nombre_key" ON "TIPO_TRANSACCION"("nombre");

-- CreateIndex
CREATE UNIQUE INDEX "METODO_PAGO_nombre_key" ON "METODO_PAGO"("nombre");

-- CreateIndex
CREATE UNIQUE INDEX "MARCA_VEHICULO_nombre_key" ON "MARCA_VEHICULO"("nombre");

-- CreateIndex
CREATE UNIQUE INDEX "COLOR_VEHICULO_nombre_key" ON "COLOR_VEHICULO"("nombre");

-- CreateIndex
CREATE UNIQUE INDEX "PERFIL_nombre_key" ON "PERFIL"("nombre");

-- CreateIndex
CREATE UNIQUE INDEX "USUARIO_correoUsu_key" ON "USUARIO"("correoUsu");

-- CreateIndex
CREATE UNIQUE INDEX "USUARIO_numeroTelefonoUsu_key" ON "USUARIO"("numeroTelefonoUsu");

-- CreateIndex
CREATE UNIQUE INDEX "VERIFICACION_CORREO_codigoVer_key" ON "VERIFICACION_CORREO"("codigoVer");

-- CreateIndex
CREATE UNIQUE INDEX "VEHICULO_placaVeh_key" ON "VEHICULO"("placaVeh");

-- CreateIndex
CREATE UNIQUE INDEX "HISTORIAL_VIAJE_idSolHis_idRutHis_key" ON "HISTORIAL_VIAJE"("idSolHis", "idRutHis");
