-- =====================================================
-- TABLA: ESTADO_USUARIO
-- =====================================================
ALTER TABLE ESTADO_USUARIO ADD CONSTRAINT PK_ESTADO_USUARIO  PRIMARY KEY (ID_EUS);
ALTER TABLE ESTADO_USUARIO ADD CONSTRAINT NN_NOMBRE_EUS      CHECK (NOMBRE_EUS IS NOT NULL);
ALTER TABLE ESTADO_USUARIO ADD CONSTRAINT NN_DESCRIPCION_EUS CHECK (DESCRIPCION_EUS IS NOT NULL);


-- =====================================================
-- TABLA: USUARIO
-- =====================================================
ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO         PRIMARY KEY (DOCUMENTO_USU);
ALTER TABLE USUARIO ADD CONSTRAINT FK_EUS_USUARIO      FOREIGN KEY (ID_EST_USU)  REFERENCES ESTADO_USUARIO(ID_EUS);
ALTER TABLE USUARIO ADD CONSTRAINT UQ_CORREO_USU       UNIQUE (CORREO_USU);
ALTER TABLE USUARIO ADD CONSTRAINT UQ_TELEFONO_USU     UNIQUE (NUMERO_TELEFONO_USU);
ALTER TABLE USUARIO ADD CONSTRAINT NN_NOMBRES_USU      CHECK (NOMBRES_USU IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT NN_PRIMER_APE_USU   CHECK (PRIMER_APELLIDO_USU IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT NN_CORREO_USU       CHECK (CORREO_USU IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT NN_TELEFONO_USU     CHECK (NUMERO_TELEFONO_USU IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT NN_FECHA_NAC_USU    CHECK (FECHA_NACIMIENTO_USU IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT NN_CONTRASENA_USU   CHECK (CONTRASENA_USU IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT NN_FOTO_URL_USU     CHECK (FOTO_URL_USU IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT NN_SALDO_USU        CHECK (SALDO_CARTERA_USU IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT NN_FECHA_CRE_USU    CHECK (FECHA_CREACION_USU IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT NN_ID_EST_USU       CHECK (ID_EST_USU IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT CK_SALDO_USU        CHECK (SALDO_CARTERA_USU >= 0);
ALTER TABLE USUARIO ADD CONSTRAINT CK_CORREO_USU       CHECK (CORREO_USU LIKE '%@%.%');


-- =====================================================
-- TABLA: PERFIL
-- =====================================================
ALTER TABLE PERFIL ADD CONSTRAINT PK_TIPO        PRIMARY KEY (ID_PER);
ALTER TABLE PERFIL ADD CONSTRAINT UQ_NOMBRE_PER  UNIQUE (NOMBRE_PER);
ALTER TABLE PERFIL ADD CONSTRAINT NN_NOMBRE_PER  CHECK (NOMBRE_PER IS NOT NULL);
ALTER TABLE PERFIL ADD CONSTRAINT NN_DESC_PER    CHECK (DESCRIPCION_PER IS NOT NULL);
ALTER TABLE PERFIL ADD CONSTRAINT NN_FECHA_PER   CHECK (FECHA_CREACION_PER IS NOT NULL);


-- =====================================================
-- TABLA: MENU
-- =====================================================
ALTER TABLE MENU ADD CONSTRAINT PK_NAVEGACION PRIMARY KEY (ID_MEN);
ALTER TABLE MENU ADD CONSTRAINT FK_MENU_MENU  FOREIGN KEY (URL_PADRE_MEN) REFERENCES MENU(ID_MEN);
ALTER TABLE MENU ADD CONSTRAINT NN_URL_MEN    CHECK (URL_MEN IS NOT NULL);
ALTER TABLE MENU ADD CONSTRAINT NN_NOMBRE_MEN CHECK (NOMBRE_MEN IS NOT NULL);
ALTER TABLE MENU ADD CONSTRAINT NN_ORDEN_MEN  CHECK (ORDEN_MEN IS NOT NULL);
ALTER TABLE MENU ADD CONSTRAINT CK_ORDEN_MEN  CHECK (ORDEN_MEN > 0);


-- =====================================================
-- TABLA: MENU_PERFIL
-- =====================================================
ALTER TABLE MENU_PERFIL ADD CONSTRAINT PK_MENU_PERFIL PRIMARY KEY (ID_PERFIL_MPE, ID_MENU_MPE);
ALTER TABLE MENU_PERFIL ADD CONSTRAINT FK_MPE_MENU    FOREIGN KEY (ID_MENU_MPE)   REFERENCES MENU(ID_MEN);
ALTER TABLE MENU_PERFIL ADD CONSTRAINT FK_MPE_PERFIL  FOREIGN KEY (ID_PERFIL_MPE) REFERENCES PERFIL(ID_PER);
ALTER TABLE MENU_PERFIL ADD CONSTRAINT NN_INSERT_MPE  CHECK (INSERT_MPE IS NOT NULL);
ALTER TABLE MENU_PERFIL ADD CONSTRAINT NN_UPDATE_MPE  CHECK (UPDATE_MPE IS NOT NULL);
ALTER TABLE MENU_PERFIL ADD CONSTRAINT NN_DELETE_MPE  CHECK (DELETE_MPE IS NOT NULL);
ALTER TABLE MENU_PERFIL ADD CONSTRAINT NN_SELECT_MPE  CHECK (SELECT_MPE IS NOT NULL);
ALTER TABLE MENU_PERFIL ADD CONSTRAINT CK_INSERT_MPE  CHECK (INSERT_MPE IN ('S', 'N'));
ALTER TABLE MENU_PERFIL ADD CONSTRAINT CK_UPDATE_MPE  CHECK (UPDATE_MPE IN ('S', 'N'));
ALTER TABLE MENU_PERFIL ADD CONSTRAINT CK_DELETE_MPE  CHECK (DELETE_MPE IN ('S', 'N'));
ALTER TABLE MENU_PERFIL ADD CONSTRAINT CK_SELECT_MPE  CHECK (SELECT_MPE IN ('S', 'N'));


-- =====================================================
-- TABLA: USUARIO_PERFIL
-- =====================================================
ALTER TABLE USUARIO_PERFIL ADD CONSTRAINT PK_PERFIL           PRIMARY KEY (ID_UPE);
ALTER TABLE USUARIO_PERFIL ADD CONSTRAINT FK_UPE_USUARIO      FOREIGN KEY (DOCUMENTO_USU_UPE) REFERENCES USUARIO(DOCUMENTO_USU);
ALTER TABLE USUARIO_PERFIL ADD CONSTRAINT FK_UPE_PERFIL       FOREIGN KEY (ID_PER_UPE)        REFERENCES PERFIL(ID_PER);
ALTER TABLE USUARIO_PERFIL ADD CONSTRAINT NN_DOC_USU_UPE      CHECK (DOCUMENTO_USU_UPE IS NOT NULL);
ALTER TABLE USUARIO_PERFIL ADD CONSTRAINT NN_ID_PER_UPE       CHECK (ID_PER_UPE IS NOT NULL);
ALTER TABLE USUARIO_PERFIL ADD CONSTRAINT NN_CALIFICACION_UPE CHECK (CALIFICACION_UPE IS NOT NULL);
ALTER TABLE USUARIO_PERFIL ADD CONSTRAINT NN_FECHA_ASI_UPE    CHECK (FECHA_ASIGNACION_UPE IS NOT NULL);
ALTER TABLE USUARIO_PERFIL ADD CONSTRAINT CK_CALIFICACION_UPE CHECK (CALIFICACION_UPE BETWEEN 0 AND 5);


-- =====================================================
-- TABLA: MARCA_VEHICULO
-- =====================================================
ALTER TABLE MARCA_VEHICULO ADD CONSTRAINT PK_MARCA_VEHICULO PRIMARY KEY (ID_MAR);
ALTER TABLE MARCA_VEHICULO ADD CONSTRAINT UQ_NOMBRE_MAR     UNIQUE (NOMBRE_MAR);
ALTER TABLE MARCA_VEHICULO ADD CONSTRAINT NN_NOMBRE_MAR     CHECK (NOMBRE_MAR IS NOT NULL);


-- =====================================================
-- TABLA: MODELO_VEHICULO
-- =====================================================
ALTER TABLE MODELO_VEHICULO ADD CONSTRAINT PK_MODELO_VEHICULO PRIMARY KEY (ID_MOD);
ALTER TABLE MODELO_VEHICULO ADD CONSTRAINT NN_NOMBRE_MOD      CHECK (NOMBRE_MOD IS NOT NULL);
ALTER TABLE MODELO_VEHICULO ADD CONSTRAINT NN_ANIO_MOD        CHECK (ANIO_MOD IS NOT NULL);
ALTER TABLE MODELO_VEHICULO ADD CONSTRAINT CK_ANIO_MOD        CHECK (ANIO_MOD BETWEEN 1990 AND 2100);


-- =====================================================
-- TABLA: COLOR_VEHICULO
-- =====================================================
ALTER TABLE COLOR_VEHICULO ADD CONSTRAINT PK_COLOR_VEHICULO PRIMARY KEY (ID_COL);
ALTER TABLE COLOR_VEHICULO ADD CONSTRAINT UQ_NOMBRE_COL     UNIQUE (NOMBRE_COL);
ALTER TABLE COLOR_VEHICULO ADD CONSTRAINT NN_NOMBRE_COL     CHECK (NOMBRE_COL IS NOT NULL);


-- =====================================================
-- TABLA: ESTADO_VEHICULO
-- =====================================================
ALTER TABLE ESTADO_VEHICULO ADD CONSTRAINT PK_ESTADO_VEHICULO PRIMARY KEY (ID_EVE);
ALTER TABLE ESTADO_VEHICULO ADD CONSTRAINT NN_NOMBRE_EVE      CHECK (NOMBRE_EVE IS NOT NULL);


-- =====================================================
-- TABLA: VEHICULO
-- =====================================================
ALTER TABLE VEHICULO ADD CONSTRAINT PK_VEHICULO              PRIMARY KEY (ID_VEH);
ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEH_MARCA_VEHICULO    FOREIGN KEY (ID_MAR_VEH)        REFERENCES MARCA_VEHICULO(ID_MAR);
ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEH_MODELO_VEHICULO   FOREIGN KEY (ID_MOD_VEH)        REFERENCES MODELO_VEHICULO(ID_MOD);
ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEH_COLOR_VEHICULO    FOREIGN KEY (ID_COL_VEH)        REFERENCES COLOR_VEHICULO(ID_COL);
ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEH_ESTADO_VEHICULO   FOREIGN KEY (ID_EST_VEH)        REFERENCES ESTADO_VEHICULO(ID_EVE);
ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEH_USUARIO           FOREIGN KEY (DOCUMENTO_USU_VEH) REFERENCES USUARIO(DOCUMENTO_USU);
ALTER TABLE VEHICULO ADD CONSTRAINT UQ_PLACA_VEH             UNIQUE (PLACA_VEH);
ALTER TABLE VEHICULO ADD CONSTRAINT NN_DOC_USU_VEH           CHECK (DOCUMENTO_USU_VEH IS NOT NULL);
ALTER TABLE VEHICULO ADD CONSTRAINT NN_ID_MAR_VEH            CHECK (ID_MAR_VEH IS NOT NULL);
ALTER TABLE VEHICULO ADD CONSTRAINT NN_ID_MOD_VEH            CHECK (ID_MOD_VEH IS NOT NULL);
ALTER TABLE VEHICULO ADD CONSTRAINT NN_ID_COL_VEH            CHECK (ID_COL_VEH IS NOT NULL);
ALTER TABLE VEHICULO ADD CONSTRAINT NN_ID_EST_VEH            CHECK (ID_EST_VEH IS NOT NULL);
ALTER TABLE VEHICULO ADD CONSTRAINT NN_PLACA_VEH             CHECK (PLACA_VEH IS NOT NULL);
ALTER TABLE VEHICULO ADD CONSTRAINT NN_SOAT_URL_VEH          CHECK (SOAT_URL_VEH IS NOT NULL);
ALTER TABLE VEHICULO ADD CONSTRAINT NN_LICENCIA_URL_VEH      CHECK (LICENCIA_URL_VEH IS NOT NULL);
ALTER TABLE VEHICULO ADD CONSTRAINT NN_TARJETA_URL_VEH       CHECK (TARJETA_URL_VEH IS NOT NULL);
ALTER TABLE VEHICULO ADD CONSTRAINT NN_VEHICULO_URL_VEH      CHECK (VEHICULO_URL_VEH IS NOT NULL);
ALTER TABLE VEHICULO ADD CONSTRAINT NN_FECHA_REG_VEH         CHECK (FECHA_REGISTRO_VEH IS NOT NULL);


-- =====================================================
-- TABLA: ESTADO_RUTA
-- =====================================================
ALTER TABLE ESTADO_RUTA ADD CONSTRAINT PK_ESTADO_RUTA PRIMARY KEY (ID_ERU);
ALTER TABLE ESTADO_RUTA ADD CONSTRAINT NN_NOMBRE_ERU  CHECK (NOMBRE_ERU IS NOT NULL);


-- =====================================================
-- TABLA: RUTA
-- =====================================================
ALTER TABLE RUTA ADD CONSTRAINT PK_RUTA               PRIMARY KEY (ID_RUT);
ALTER TABLE RUTA ADD CONSTRAINT FK_RUT_USUARIO_PERFIL FOREIGN KEY (ID_UPE_RUT) REFERENCES USUARIO_PERFIL(ID_UPE);
ALTER TABLE RUTA ADD CONSTRAINT FK_RUT_VEHICULO        FOREIGN KEY (ID_VEH_RUT) REFERENCES VEHICULO(ID_VEH);
ALTER TABLE RUTA ADD CONSTRAINT FK_RUT_ESTADO_RUTA     FOREIGN KEY (ID_EST_RUT) REFERENCES ESTADO_RUTA(ID_ERU);
ALTER TABLE RUTA ADD CONSTRAINT NN_ID_UPE_RUT          CHECK (ID_UPE_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_ID_VEH_RUT          CHECK (ID_VEH_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_ID_EST_RUT          CHECK (ID_EST_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_LAT_ORIGEN_RUT      CHECK (LATITUD_ORIGEN_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_LON_ORIGEN_RUT      CHECK (LONGITUD_ORIGEN_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_LAT_DESTINO_RUT     CHECK (LATITUD_DESTINO_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_LON_DESTINO_RUT     CHECK (LONGITUD_DESTINO_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_HORA_SALIDA_RUT     CHECK (HORA_SALIDA_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_CUPOS_TOT_RUT       CHECK (CUPOS_TOTALES_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_CUPOS_DISP_RUT      CHECK (CUPOS_DISPONIBLES_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_PRECIO_RUT          CHECK (PRECIO_CUPO_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_DISTANCIA_RUT       CHECK (DISTANCIA_KM_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_FECHA_CRE_RUT       CHECK (FECHA_CREACION_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT NN_UPDATED_AT_RUT      CHECK (UPDATED_AT_RUT IS NOT NULL);
ALTER TABLE RUTA ADD CONSTRAINT CK_CUPOS_TOTALES       CHECK (CUPOS_TOTALES_RUT BETWEEN 1 AND 4);
ALTER TABLE RUTA ADD CONSTRAINT CK_CUPOS_DISP          CHECK (CUPOS_DISPONIBLES_RUT >= 0);
ALTER TABLE RUTA ADD CONSTRAINT CK_PRECIO_RUT_VAL      CHECK (PRECIO_CUPO_RUT >= 0);


-- =====================================================
-- TABLA: PUNTO_ENCUENTRO
-- =====================================================
ALTER TABLE PUNTO_ENCUENTRO ADD CONSTRAINT PK_PUNTO_ENCUENTRO PRIMARY KEY (ID_PEN);
ALTER TABLE PUNTO_ENCUENTRO ADD CONSTRAINT FK_PEN_RUTA        FOREIGN KEY (ID_RUT_PEN) REFERENCES RUTA(ID_RUT);
ALTER TABLE PUNTO_ENCUENTRO ADD CONSTRAINT NN_ID_RUT_PEN      CHECK (ID_RUT_PEN IS NOT NULL);
ALTER TABLE PUNTO_ENCUENTRO ADD CONSTRAINT NN_LATITUD_PEN     CHECK (LATITUD_PEN IS NOT NULL);
ALTER TABLE PUNTO_ENCUENTRO ADD CONSTRAINT NN_LONGITUD_PEN    CHECK (LONGITUD_PEN IS NOT NULL);
ALTER TABLE PUNTO_ENCUENTRO ADD CONSTRAINT NN_ORDEN_PEN       CHECK (ORDEN_PEN IS NOT NULL);
ALTER TABLE PUNTO_ENCUENTRO ADD CONSTRAINT CK_ORDEN_PEN       CHECK (ORDEN_PEN > 0);


-- =====================================================
-- TABLA: ESTADO_SOLICITUD
-- =====================================================
ALTER TABLE ESTADO_SOLICITUD ADD CONSTRAINT PK_ESTADO_SOLICITUD PRIMARY KEY (ID_ESO);
ALTER TABLE ESTADO_SOLICITUD ADD CONSTRAINT NN_NOMBRE_ESO       CHECK (NOMBRE_ESO IS NOT NULL);


-- =====================================================
-- TABLA: METODO_PAGO
-- =====================================================
ALTER TABLE METODO_PAGO ADD CONSTRAINT PK_METODO_PAGO PRIMARY KEY (ID_MPA);
ALTER TABLE METODO_PAGO ADD CONSTRAINT UQ_NOMBRE_MPA  UNIQUE (NOMBRE_MPA);
ALTER TABLE METODO_PAGO ADD CONSTRAINT NN_NOMBRE_MPA  CHECK (NOMBRE_MPA IS NOT NULL);


-- =====================================================
-- TABLA: SOLICITUD_CUPO
-- =====================================================
ALTER TABLE SOLICITUD_CUPO ADD CONSTRAINT PK_SOLICITUD_CUPO         PRIMARY KEY (ID_SOL);
ALTER TABLE SOLICITUD_CUPO ADD CONSTRAINT FK_SOL_USUARIO_PERFIL     FOREIGN KEY (ID_UPE_SOL) REFERENCES USUARIO_PERFIL(ID_UPE);
ALTER TABLE SOLICITUD_CUPO ADD CONSTRAINT FK_SOL_RUTA               FOREIGN KEY (ID_RUT_SOL) REFERENCES RUTA(ID_RUT);
ALTER TABLE SOLICITUD_CUPO ADD CONSTRAINT FK_SOL_ESTADO_SOLICITUD   FOREIGN KEY (ID_ESO_SOL) REFERENCES ESTADO_SOLICITUD(ID_ESO);
ALTER TABLE SOLICITUD_CUPO ADD CONSTRAINT FK_SOL_METODO_PAGO        FOREIGN KEY (ID_MPA_SOL) REFERENCES METODO_PAGO(ID_MPA);
ALTER TABLE SOLICITUD_CUPO ADD CONSTRAINT NN_ID_UPE_SOL             CHECK (ID_UPE_SOL IS NOT NULL);
ALTER TABLE SOLICITUD_CUPO ADD CONSTRAINT NN_ID_RUT_SOL             CHECK (ID_RUT_SOL IS NOT NULL);
ALTER TABLE SOLICITUD_CUPO ADD CONSTRAINT NN_ID_ESO_SOL             CHECK (ID_ESO_SOL IS NOT NULL);
ALTER TABLE SOLICITUD_CUPO ADD CONSTRAINT NN_ID_MPA_SOL             CHECK (ID_MPA_SOL IS NOT NULL);
ALTER TABLE SOLICITUD_CUPO ADD CONSTRAINT NN_MONTO_SOL              CHECK (MONTO_SOL IS NOT NULL);
ALTER TABLE SOLICITUD_CUPO ADD CONSTRAINT NN_FECHA_CRE_SOL          CHECK (FECHA_CREACION_SOL IS NOT NULL);
ALTER TABLE SOLICITUD_CUPO ADD CONSTRAINT CK_MONTO_SOL              CHECK (MONTO_SOL >= 0);


-- =====================================================
-- TABLA: ESTADO_CUPO_RUTA
-- =====================================================
ALTER TABLE ESTADO_CUPO_RUTA ADD CONSTRAINT PK_ESTADO_CUPO_RUTA PRIMARY KEY (ID_ECU);
ALTER TABLE ESTADO_CUPO_RUTA ADD CONSTRAINT NN_NOMBRE_ECU       CHECK (NOMBRE_ECU IS NOT NULL);


-- =====================================================
-- TABLA: CUPO_RUTA
-- =====================================================
ALTER TABLE CUPO_RUTA ADD CONSTRAINT PK_CUPO_RUTA            PRIMARY KEY (ID_SOL_CRU, ID_RUT_CRU);
ALTER TABLE CUPO_RUTA ADD CONSTRAINT FK_CRU_ESTADO_CUPO_RUTA FOREIGN KEY (ID_ECU_CRU) REFERENCES ESTADO_CUPO_RUTA(ID_ECU);
ALTER TABLE CUPO_RUTA ADD CONSTRAINT FK_CRU_SOLICITUD_CUPO   FOREIGN KEY (ID_SOL_CRU) REFERENCES SOLICITUD_CUPO(ID_SOL);
ALTER TABLE CUPO_RUTA ADD CONSTRAINT FK_CRU_RUTA             FOREIGN KEY (ID_RUT_CRU) REFERENCES RUTA(ID_RUT);
ALTER TABLE CUPO_RUTA ADD CONSTRAINT NN_ID_ECU_CRU           CHECK (ID_ECU_CRU IS NOT NULL);
ALTER TABLE CUPO_RUTA ADD CONSTRAINT NN_FECHA_APR_CRU        CHECK (FECHA_APROBACION_CRU IS NOT NULL);


-- =====================================================
-- TABLA: HISTORIAL_VIAJE
-- =====================================================
ALTER TABLE HISTORIAL_VIAJE ADD CONSTRAINT PK_HISTORIAL_VIAJE PRIMARY KEY (ID_HIS);
ALTER TABLE HISTORIAL_VIAJE ADD CONSTRAINT FK_HIS_CUPO_RUTA   FOREIGN KEY (SOL_ID_HIS, RUT_ID_HIS) REFERENCES CUPO_RUTA(ID_SOL_CRU, ID_RUT_CRU);
ALTER TABLE HISTORIAL_VIAJE ADD CONSTRAINT NN_SOL_ID_HIS      CHECK (SOL_ID_HIS IS NOT NULL);
ALTER TABLE HISTORIAL_VIAJE ADD CONSTRAINT NN_RUT_ID_HIS      CHECK (RUT_ID_HIS IS NOT NULL);
ALTER TABLE HISTORIAL_VIAJE ADD CONSTRAINT NN_DOC_USU_HIS     CHECK (DOCUMENTO_USU_HIS IS NOT NULL);
ALTER TABLE HISTORIAL_VIAJE ADD CONSTRAINT NN_ROL_VIAJE_HIS   CHECK (ROL_VIAJE_HIS IS NOT NULL);
ALTER TABLE HISTORIAL_VIAJE ADD CONSTRAINT NN_FECHA_VIA_HIS   CHECK (FECHA_VIAJE_HIS IS NOT NULL);
ALTER TABLE HISTORIAL_VIAJE ADD CONSTRAINT CK_ROL_VIAJE       CHECK (ROL_VIAJE_HIS IN ('PASAJERO', 'CONDUCTOR'));


-- =====================================================
-- TABLA: CALIFICACION
-- =====================================================
ALTER TABLE CALIFICACION ADD CONSTRAINT PK_CALIFICACION     PRIMARY KEY (ID_CAL);
ALTER TABLE CALIFICACION ADD CONSTRAINT FK_CAL_CUPO_RUTA    FOREIGN KEY (SOL_ID_CAL, RUT_ID_CAL) REFERENCES CUPO_RUTA(ID_SOL_CRU, ID_RUT_CRU);
ALTER TABLE CALIFICACION ADD CONSTRAINT NN_SOL_ID_CAL       CHECK (SOL_ID_CAL IS NOT NULL);
ALTER TABLE CALIFICACION ADD CONSTRAINT NN_RUT_ID_CAL       CHECK (RUT_ID_CAL IS NOT NULL);
ALTER TABLE CALIFICACION ADD CONSTRAINT NN_DOC_CALIF_CAL    CHECK (DOCUMENTO_CALIFICADOR_CAL IS NOT NULL);
ALTER TABLE CALIFICACION ADD CONSTRAINT NN_DOC_CADO_CAL     CHECK (DOCUMENTO_CALIFICADO_CAL IS NOT NULL);
ALTER TABLE CALIFICACION ADD CONSTRAINT NN_PUNTAJE_CAL      CHECK (PUNTAJE_CAL IS NOT NULL);
ALTER TABLE CALIFICACION ADD CONSTRAINT NN_ROL_CALIF_CAL    CHECK (ROL_CALIFICADOR_CAL IS NOT NULL);
ALTER TABLE CALIFICACION ADD CONSTRAINT NN_FECHA_CRE_CAL    CHECK (FECHA_CREACION_CAL IS NOT NULL);
ALTER TABLE CALIFICACION ADD CONSTRAINT CK_PUNTAJE_CAL      CHECK (PUNTAJE_CAL BETWEEN 1 AND 5);
ALTER TABLE CALIFICACION ADD CONSTRAINT CK_ROL_CALIFICADOR  CHECK (ROL_CALIFICADOR_CAL IN ('PASAJERO', 'CONDUCTOR'));


-- =====================================================
-- TABLA: VERIFICACION_CORREO
-- =====================================================
ALTER TABLE VERIFICACION_CORREO ADD CONSTRAINT PK_VERIFICACION_CORREO PRIMARY KEY (ID_VER);
ALTER TABLE VERIFICACION_CORREO ADD CONSTRAINT FK_VER_USUARIO         FOREIGN KEY (DOCUMENTO_USU_VER) REFERENCES USUARIO(DOCUMENTO_USU);
ALTER TABLE VERIFICACION_CORREO ADD CONSTRAINT NN_DOC_USU_VER         CHECK (DOCUMENTO_USU_VER IS NOT NULL);
ALTER TABLE VERIFICACION_CORREO ADD CONSTRAINT NN_CODIGO_VER          CHECK (CODIGO_VER IS NOT NULL);
ALTER TABLE VERIFICACION_CORREO ADD CONSTRAINT NN_FECHA_EXP_VER       CHECK (FECHA_EXPIRACION_VER IS NOT NULL);
ALTER TABLE VERIFICACION_CORREO ADD CONSTRAINT NN_USADO_VER           CHECK (USADO_VER IS NOT NULL);
ALTER TABLE VERIFICACION_CORREO ADD CONSTRAINT NN_FECHA_CRE_VER       CHECK (FECHA_CREACION_VER IS NOT NULL);
ALTER TABLE VERIFICACION_CORREO ADD CONSTRAINT CK_USADO_VER           CHECK (USADO_VER IN ('S', 'N'));


-- =====================================================
-- TABLA: TIPO_TRANSACCION
-- =====================================================
ALTER TABLE TIPO_TRANSACCION ADD CONSTRAINT PK_TIPO_TRANSACCION PRIMARY KEY (ID_TTR);
ALTER TABLE TIPO_TRANSACCION ADD CONSTRAINT NN_NOMBRE_TTR       CHECK (NOMBRE_TTR IS NOT NULL);
ALTER TABLE TIPO_TRANSACCION ADD CONSTRAINT NN_DESC_TTR         CHECK (DESCRIPCION_TTR IS NOT NULL);
ALTER TABLE TIPO_TRANSACCION ADD CONSTRAINT CK_TTR_NOMBRE       CHECK (NOMBRE_TTR IN ('RECARGA', 'PAGO_VIAJE', 'REEMBOLSO', 'RETIRO'));


-- =====================================================
-- TABLA: TRANSACCIONES_CARTERA
-- =====================================================
ALTER TABLE TRANSACCIONES_CARTERA ADD CONSTRAINT PK_TRANSACCIONES_CARTERA PRIMARY KEY (ID_TRA);
ALTER TABLE TRANSACCIONES_CARTERA ADD CONSTRAINT FK_TRA_USUARIO            FOREIGN KEY (DOCUMENTO_USU_TRA) REFERENCES USUARIO(DOCUMENTO_USU);
ALTER TABLE TRANSACCIONES_CARTERA ADD CONSTRAINT FK_TRA_TIPO_TRANSACCION   FOREIGN KEY (ID_TTR_TRA)        REFERENCES TIPO_TRANSACCION(ID_TTR);
ALTER TABLE TRANSACCIONES_CARTERA ADD CONSTRAINT NN_DOC_USU_TRA            CHECK (DOCUMENTO_USU_TRA IS NOT NULL);
ALTER TABLE TRANSACCIONES_CARTERA ADD CONSTRAINT NN_ID_TTR_TRA             CHECK (ID_TTR_TRA IS NOT NULL);
ALTER TABLE TRANSACCIONES_CARTERA ADD CONSTRAINT NN_MONTO_TRA              CHECK (MONTO_TRA IS NOT NULL);
ALTER TABLE TRANSACCIONES_CARTERA ADD CONSTRAINT NN_SALDO_RES_TRA          CHECK (SALDO_RESULTANTE_TRA IS NOT NULL);
ALTER TABLE TRANSACCIONES_CARTERA ADD CONSTRAINT NN_FECHA_REA_TRA          CHECK (FECHA_REALIZACION_TRA IS NOT NULL);
ALTER TABLE TRANSACCIONES_CARTERA ADD CONSTRAINT CK_MONTO_TRA              CHECK (MONTO_TRA > 0);
ALTER TABLE TRANSACCIONES_CARTERA ADD CONSTRAINT CK_SALDO_RES              CHECK (SALDO_RESULTANTE_TRA >= 0);


prompt =====================================================
prompt Módulo 2 ejecutado: Constraints - VamonosPues
prompt =====================================================