-- =====================================================
-- SECCIÓN 1: ELIMINAR TABLAS (orden inverso por FKs)
-- =====================================================

DROP TABLE CALIFICACION;
DROP TABLE HISTORIAL_VIAJE;
DROP TABLE CUPO_RUTA;
DROP TABLE SOLICITUD_CUPO;
DROP TABLE PUNTO_ENCUENTRO;
DROP TABLE RUTA;
DROP TABLE VEHICULO;
DROP TABLE VERIFICACION_CORREO;
DROP TABLE TRANSACCIONES_CARTERA;
DROP TABLE USUARIO_PERFIL;
DROP TABLE MENU_PERFIL;
DROP TABLE USUARIO;
DROP TABLE PERFIL;
DROP TABLE MENU;
DROP TABLE MARCA_VEHICULO;
DROP TABLE MODELO_VEHICULO;
DROP TABLE COLOR_VEHICULO;
DROP TABLE ESTADO_VEHICULO;
DROP TABLE ESTADO_RUTA;
DROP TABLE ESTADO_SOLICITUD;
DROP TABLE METODO_PAGO;
DROP TABLE ESTADO_CUPO_RUTA;
DROP TABLE TIPO_TRANSACCION;
DROP TABLE ESTADO_USUARIO;


-- =====================================================
-- SECCIÓN 2: ELIMINAR SECUENCIAS
-- =====================================================

DROP SEQUENCE SEQ_PERFIL;
DROP SEQUENCE SEQ_MENU;
DROP SEQUENCE SEQ_USUARIO_PERFIL;
DROP SEQUENCE SEQ_VEHICULO;
DROP SEQUENCE SEQ_RUTA;
DROP SEQUENCE SEQ_PUNTO_ENCUENTRO;
DROP SEQUENCE SEQ_SOLICITUD_CUPO;
DROP SEQUENCE SEQ_HISTORIAL_VIAJE;
DROP SEQUENCE SEQ_CALIFICACION;
DROP SEQUENCE SEQ_VERIFICACION_CORREO;
DROP SEQUENCE SEQ_TRANSACCIONES_CARTERA;
DROP SEQUENCE SEQ_MARCA_VEHICULO;
DROP SEQUENCE SEQ_MODELO_VEHICULO;
DROP SEQUENCE SEQ_COLOR_VEHICULO;
DROP SEQUENCE SEQ_ESTADO_VEHICULO;
DROP SEQUENCE SEQ_ESTADO_RUTA;
DROP SEQUENCE SEQ_ESTADO_SOLICITUD;
DROP SEQUENCE SEQ_METODO_PAGO;
DROP SEQUENCE SEQ_ESTADO_CUPO_RUTA;
DROP SEQUENCE SEQ_TIPO_TRANSACCION;
DROP SEQUENCE SEQ_ESTADO_USUARIO;
DROP SEQUENCE SEQ_MENU_PERFIL;


-- =====================================================
-- SECCIÓN 3: CREAR SECUENCIAS
-- =====================================================

CREATE SEQUENCE SEQ_PERFIL              START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MENU                START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIO_PERFIL      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VEHICULO            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RUTA                START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PUNTO_ENCUENTRO     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SOLICITUD_CUPO      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HISTORIAL_VIAJE     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CALIFICACION        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VERIFICACION_CORREO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRANSACCIONES_CARTERA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MARCA_VEHICULO      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MODELO_VEHICULO     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COLOR_VEHICULO      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ESTADO_VEHICULO     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ESTADO_RUTA         START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ESTADO_SOLICITUD    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_METODO_PAGO         START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ESTADO_CUPO_RUTA    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TIPO_TRANSACCION    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ESTADO_USUARIO      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MENU_PERFIL         START WITH 1 INCREMENT BY 1 NOCACHE;


-- =====================================================
-- SECCIÓN 4: CREAR TABLAS
-- =====================================================

-- Tabla: ESTADO_USUARIO
CREATE TABLE ESTADO_USUARIO (
    ID_EUS          INTEGER,
    NOMBRE_EUS      VARCHAR2(20 BYTE),
    DESCRIPCION_EUS VARCHAR2(150 BYTE)
) TABLESPACE TS_VamonosPues;

-- Tabla: USUARIO
CREATE TABLE USUARIO (
    DOCUMENTO_USU        VARCHAR2(10 BYTE),
    NOMBRES_USU          VARCHAR2(80 BYTE),
    PRIMER_APELLIDO_USU  VARCHAR2(40 BYTE),
    SEGUNDO_APELLIDO_USU VARCHAR2(40 BYTE),
    CORREO_USU           VARCHAR2(150 BYTE),
    NUMERO_TELEFONO_USU  VARCHAR2(13 BYTE),
    FECHA_NACIMIENTO_USU DATE,
    CONTRASENA_USU       VARCHAR2(100 BYTE),
    FOTO_URL_USU         VARCHAR2(500 BYTE),
    SALDO_CARTERA_USU    NUMBER(7,2),
    FECHA_CREACION_USU   DATE,
    ID_EST_USU           INTEGER
) TABLESPACE TS_VamonosPues;

-- Tabla: PERFIL
CREATE TABLE PERFIL (
    ID_PER          INTEGER,
    NOMBRE_PER      VARCHAR2(15 BYTE),
    DESCRIPCION_PER VARCHAR2(150 BYTE),
    FECHA_CREACION_PER DATE
) TABLESPACE TS_VamonosPues;

-- Tabla: MENU
CREATE TABLE MENU (
    ID_MEN        INTEGER,
    URL_MEN       VARCHAR2(500 BYTE),
    NOMBRE_MEN    VARCHAR2(50),
    URL_PADRE_MEN INTEGER,
    ORDEN_MEN     INTEGER
) TABLESPACE TS_VamonosPues;

-- Tabla: MENU_PERFIL
CREATE TABLE MENU_PERFIL (
    ID_MENU_MPE    INTEGER,
    ID_PERFIL_MPE  INTEGER,
    INSERT_MPE     VARCHAR2(1 CHAR),
    UPDATE_MPE     VARCHAR2(1 CHAR),
    DELETE_MPE     VARCHAR2(1 CHAR),
    SELECT_MPE     VARCHAR2(1 CHAR)
) TABLESPACE TS_VamonosPues;

-- Tabla: USUARIO_PERFIL
CREATE TABLE USUARIO_PERFIL (
    ID_UPE               INTEGER,
    DOCUMENTO_USU_UPE    VARCHAR2(10 BYTE),
    ID_PER_UPE           INTEGER,
    CALIFICACION_UPE     NUMBER(2,1),
    FECHA_ASIGNACION_UPE DATE
) TABLESPACE TS_VamonosPues;

-- Tabla: MARCA_VEHICULO
CREATE TABLE MARCA_VEHICULO (
    ID_MAR      INTEGER,
    NOMBRE_MAR  VARCHAR2(30 BYTE)
) TABLESPACE TS_VamonosPues;

-- Tabla: MODELO_VEHICULO
CREATE TABLE MODELO_VEHICULO (
    ID_MOD      INTEGER,
    NOMBRE_MOD  VARCHAR2(50 BYTE),
    ANIO_MOD    NUMBER(4)
) TABLESPACE TS_VamonosPues;

-- Tabla: COLOR_VEHICULO
CREATE TABLE COLOR_VEHICULO (
    ID_COL      INTEGER,
    NOMBRE_COL  VARCHAR2(30 BYTE)
) TABLESPACE TS_VamonosPues;

-- Tabla: ESTADO_VEHICULO
CREATE TABLE ESTADO_VEHICULO (
    ID_EVE      INTEGER,
    NOMBRE_EVE  VARCHAR2(20 BYTE)
) TABLESPACE TS_VamonosPues;

-- Tabla: VEHICULO
CREATE TABLE VEHICULO (
    ID_VEH              INTEGER,
    DOCUMENTO_USU_VEH   VARCHAR2(10 BYTE),
    ID_MAR_VEH          INTEGER,
    ID_MOD_VEH          INTEGER,
    ID_COL_VEH          INTEGER,
    ID_EST_VEH          INTEGER,
    PLACA_VEH           VARCHAR2(6 BYTE),
    SOAT_URL_VEH        VARCHAR2(500 BYTE),
    LICENCIA_URL_VEH    VARCHAR2(500 BYTE),
    TARJETA_URL_VEH     VARCHAR2(500 BYTE),
    VEHICULO_URL_VEH    VARCHAR2(500 BYTE),
    FECHA_REGISTRO_VEH  DATE
) TABLESPACE TS_VamonosPues;

-- Tabla: ESTADO_RUTA
CREATE TABLE ESTADO_RUTA (
    ID_ERU      INTEGER,
    NOMBRE_ERU  VARCHAR2(20 BYTE)
) TABLESPACE TS_VamonosPues;

-- Tabla: RUTA
CREATE TABLE RUTA (
    ID_RUT                  INTEGER,
    ID_UPE_RUT              INTEGER,
    ID_VEH_RUT              INTEGER,
    ID_EST_RUT              INTEGER,
    LATITUD_ORIGEN_RUT      NUMBER(9,6),
    LONGITUD_ORIGEN_RUT     NUMBER(9,6),
    LATITUD_DESTINO_RUT     NUMBER(9,6),
    LONGITUD_DESTINO_RUT    NUMBER(9,6),
    HORA_SALIDA_RUT         DATE,
    CUPOS_TOTALES_RUT       NUMBER(1),
    CUPOS_DISPONIBLES_RUT   NUMBER(1),
    PRECIO_CUPO_RUT         NUMBER(7,2),
    DISTANCIA_KM_RUT        NUMBER(4,2),
    FECHA_CREACION_RUT      DATE,
    UPDATED_AT_RUT          DATE
) TABLESPACE TS_VamonosPues;

-- Tabla: PUNTO_ENCUENTRO
CREATE TABLE PUNTO_ENCUENTRO (
    ID_PEN       INTEGER,
    ID_RUT_PEN   INTEGER,
    LATITUD_PEN  NUMBER(9,6),
    LONGITUD_PEN NUMBER(9,6),
    ORDEN_PEN    NUMBER(1)
) TABLESPACE TS_VamonosPues;

-- Tabla: ESTADO_SOLICITUD
CREATE TABLE ESTADO_SOLICITUD (
    ID_ESO      INTEGER,
    NOMBRE_ESO  VARCHAR2(20 BYTE)
) TABLESPACE TS_VamonosPues;

-- Tabla: METODO_PAGO
CREATE TABLE METODO_PAGO (
    ID_MPA      INTEGER,
    NOMBRE_MPA  VARCHAR2(30 BYTE)
) TABLESPACE TS_VamonosPues;

-- Tabla: SOLICITUD_CUPO
CREATE TABLE SOLICITUD_CUPO (
    ID_SOL              INTEGER,
    ID_UPE_SOL          INTEGER,
    ID_RUT_SOL          INTEGER,
    ID_ESO_SOL          INTEGER,
    ID_MPA_SOL          INTEGER,
    MONTO_SOL           NUMBER(7,2),
    FECHA_CREACION_SOL  DATE
) TABLESPACE TS_VamonosPues;

-- Tabla: ESTADO_CUPO_RUTA
CREATE TABLE ESTADO_CUPO_RUTA (
    ID_ECU      INTEGER,
    NOMBRE_ECU  VARCHAR2(20 BYTE)
) TABLESPACE TS_VamonosPues;

-- Tabla: CUPO_RUTA
CREATE TABLE CUPO_RUTA (
    ID_SOL_CRU           INTEGER,
    ID_RUT_CRU           INTEGER,
    ID_ECU_CRU           INTEGER,
    FECHA_APROBACION_CRU DATE
) TABLESPACE TS_VamonosPues;

-- Tabla: HISTORIAL_VIAJE
CREATE TABLE HISTORIAL_VIAJE (
    ID_HIS              INTEGER,
    SOL_ID_HIS          INTEGER,
    RUT_ID_HIS          INTEGER,
    DOCUMENTO_USU_HIS   VARCHAR2(10 BYTE),
    ROL_VIAJE_HIS       VARCHAR2(10 BYTE),
    FECHA_VIAJE_HIS     DATE
) TABLESPACE TS_VamonosPues;

-- Tabla: CALIFICACION
CREATE TABLE CALIFICACION (
    ID_CAL                    INTEGER,
    SOL_ID_CAL                INTEGER,
    RUT_ID_CAL                INTEGER,
    DOCUMENTO_CALIFICADOR_CAL VARCHAR2(10 BYTE),
    DOCUMENTO_CALIFICADO_CAL  VARCHAR2(10 BYTE),
    PUNTAJE_CAL               NUMBER(2,1),
    COMENTARIO_CAL            VARCHAR2(300 BYTE),
    ROL_CALIFICADOR_CAL       VARCHAR2(10 BYTE),
    FECHA_CREACION_CAL        DATE
) TABLESPACE TS_VamonosPues;

-- Tabla: VERIFICACION_CORREO
CREATE TABLE VERIFICACION_CORREO (
    ID_VER               INTEGER,
    DOCUMENTO_USU_VER    VARCHAR2(10 BYTE),
    CODIGO_VER           VARCHAR2(6 BYTE),
    FECHA_EXPIRACION_VER DATE,
    USADO_VER            VARCHAR2(1 CHAR),
    FECHA_CREACION_VER   DATE
) TABLESPACE TS_VamonosPues;

-- Tabla: TIPO_TRANSACCION
CREATE TABLE TIPO_TRANSACCION (
    ID_TTR          INTEGER,
    NOMBRE_TTR      VARCHAR2(20 BYTE),
    DESCRIPCION_TTR VARCHAR2(50 BYTE)
) TABLESPACE TS_VamonosPues;

-- Tabla: TRANSACCIONES_CARTERA
CREATE TABLE TRANSACCIONES_CARTERA (
    ID_TRA                INTEGER,
    DOCUMENTO_USU_TRA     VARCHAR2(10 BYTE),
    ID_TTR_TRA            INTEGER,
    MONTO_TRA             NUMBER(7,2),
    SALDO_RESULTANTE_TRA  NUMBER(7,2),
    FECHA_REALIZACION_TRA DATE
) TABLESPACE TS_VamonosPues;


prompt =====================================================
prompt Módulo 1 ejecutado: DDL Tablas - VamonosPues
prompt =====================================================