-- =====================================================
-- SCRIPT 10: CONSTRAINTS - CONTACTOS Y FAVORITOS
-- Ejecutar despues de 9script_DDL_Contactos_Favoritos_VamonosPues.sql
-- =====================================================

-- Tabla: CONTACTO_EMERGENCIA
ALTER TABLE CONTACTO_EMERGENCIA ADD CONSTRAINT PK_CONTACTO_EMERGENCIA PRIMARY KEY (ID_CEM);
ALTER TABLE CONTACTO_EMERGENCIA ADD CONSTRAINT FK_CEM_USUARIO FOREIGN KEY (DOCUMENTO_USU_CEM) REFERENCES USUARIO(DOCUMENTO_USU);
ALTER TABLE CONTACTO_EMERGENCIA ADD CONSTRAINT UQ_CEM_USUARIO_CORREO UNIQUE (DOCUMENTO_USU_CEM, CORREO_CEM);
ALTER TABLE CONTACTO_EMERGENCIA ADD CONSTRAINT NN_DOCUMENTO_USU_CEM CHECK (DOCUMENTO_USU_CEM IS NOT NULL);
ALTER TABLE CONTACTO_EMERGENCIA ADD CONSTRAINT NN_NOMBRE_CEM CHECK (NOMBRE_CEM IS NOT NULL);
ALTER TABLE CONTACTO_EMERGENCIA ADD CONSTRAINT NN_RELACION_CEM CHECK (RELACION_CEM IS NOT NULL);
ALTER TABLE CONTACTO_EMERGENCIA ADD CONSTRAINT NN_CORREO_CEM CHECK (CORREO_CEM IS NOT NULL);
ALTER TABLE CONTACTO_EMERGENCIA ADD CONSTRAINT NN_FECHA_CREACION_CEM CHECK (FECHA_CREACION_CEM IS NOT NULL);
ALTER TABLE CONTACTO_EMERGENCIA ADD CONSTRAINT CK_NOMBRE_CEM CHECK (LENGTH(TRIM(NOMBRE_CEM)) > 0);
ALTER TABLE CONTACTO_EMERGENCIA ADD CONSTRAINT CK_RELACION_CEM CHECK (LENGTH(TRIM(RELACION_CEM)) > 0);
ALTER TABLE CONTACTO_EMERGENCIA ADD CONSTRAINT CK_CORREO_CEM_NORMALIZADO CHECK (CORREO_CEM = LOWER(TRIM(CORREO_CEM)));

-- Tabla: FAVORITO_CONDUCTOR
ALTER TABLE FAVORITO_CONDUCTOR ADD CONSTRAINT PK_FAVORITO_CONDUCTOR PRIMARY KEY (ID_FCO);
ALTER TABLE FAVORITO_CONDUCTOR ADD CONSTRAINT FK_FCO_USUARIO FOREIGN KEY (DOCUMENTO_USU_FCO) REFERENCES USUARIO(DOCUMENTO_USU);
ALTER TABLE FAVORITO_CONDUCTOR ADD CONSTRAINT FK_FCO_PERFIL_CONDUCTOR FOREIGN KEY (ID_UPE_CONDUCTOR_FCO) REFERENCES USUARIO_PERFIL(ID_UPE);
ALTER TABLE FAVORITO_CONDUCTOR ADD CONSTRAINT UQ_FCO_USUARIO_CONDUCTOR UNIQUE (DOCUMENTO_USU_FCO, ID_UPE_CONDUCTOR_FCO);
ALTER TABLE FAVORITO_CONDUCTOR ADD CONSTRAINT NN_DOCUMENTO_USU_FCO CHECK (DOCUMENTO_USU_FCO IS NOT NULL);
ALTER TABLE FAVORITO_CONDUCTOR ADD CONSTRAINT NN_ID_UPE_CONDUCTOR_FCO CHECK (ID_UPE_CONDUCTOR_FCO IS NOT NULL);
ALTER TABLE FAVORITO_CONDUCTOR ADD CONSTRAINT NN_FECHA_CREACION_FCO CHECK (FECHA_CREACION_FCO IS NOT NULL);

prompt =====================================================
prompt Modulo 10 ejecutado: Constraints Contactos y Favoritos
prompt =====================================================