-- =====================================================
-- SECCIÓN 1: INSERT - ENTIDADES FUERTES (datos base)
-- =====================================================

-- Estados de usuario
INSERT INTO ESTADO_USUARIO VALUES (SEQ_ESTADO_USUARIO.NEXTVAL, 'ACTIVO',     'Usuario activo en el sistema');
INSERT INTO ESTADO_USUARIO VALUES (SEQ_ESTADO_USUARIO.NEXTVAL, 'INACTIVO',   'Usuario desactivado');
INSERT INTO ESTADO_USUARIO VALUES (SEQ_ESTADO_USUARIO.NEXTVAL, 'SUSPENDIDO', 'Usuario suspendido por incumplimiento');
INSERT INTO ESTADO_USUARIO VALUES (SEQ_ESTADO_USUARIO.NEXTVAL, 'PENDIENTE',  'Cuenta pendiente de verificacion');

-- Perfiles
INSERT INTO PERFIL VALUES (SEQ_PERFIL.NEXTVAL, 'PASAJERO',  'Usuario que solicita cupos en rutas', SYSDATE);
INSERT INTO PERFIL VALUES (SEQ_PERFIL.NEXTVAL, 'CONDUCTOR', 'Usuario que publica rutas y conduce', SYSDATE);
INSERT INTO PERFIL VALUES (SEQ_PERFIL.NEXTVAL, 'ADMIN',     'Administrador del sistema',           SYSDATE);

-- Marcas de vehiculo
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'CHEVROLET');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'RENAULT');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'MAZDA');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'KIA');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'TOYOTA');

-- Modelos de vehiculo
INSERT INTO MODELO_VEHICULO VALUES (SEQ_MODELO_VEHICULO.NEXTVAL, 'SPARK',   2020);
INSERT INTO MODELO_VEHICULO VALUES (SEQ_MODELO_VEHICULO.NEXTVAL, 'SAIL',    2021);
INSERT INTO MODELO_VEHICULO VALUES (SEQ_MODELO_VEHICULO.NEXTVAL, 'LOGAN',   2019);
INSERT INTO MODELO_VEHICULO VALUES (SEQ_MODELO_VEHICULO.NEXTVAL, 'SANDERO', 2022);
INSERT INTO MODELO_VEHICULO VALUES (SEQ_MODELO_VEHICULO.NEXTVAL, 'CX-3',    2020);

-- Relaciones Marca-Modelo (válidas combinaciones)
-- CHEVROLET: SPARK, SAIL
INSERT INTO MARCA_MODELO_VEH VALUES (SEQ_MARCA_MODELO_VEH.NEXTVAL, 1, 1, SYSDATE);
INSERT INTO MARCA_MODELO_VEH VALUES (SEQ_MARCA_MODELO_VEH.NEXTVAL, 1, 2, SYSDATE);
-- RENAULT: LOGAN, SANDERO
INSERT INTO MARCA_MODELO_VEH VALUES (SEQ_MARCA_MODELO_VEH.NEXTVAL, 2, 3, SYSDATE);
INSERT INTO MARCA_MODELO_VEH VALUES (SEQ_MARCA_MODELO_VEH.NEXTVAL, 2, 4, SYSDATE);
-- MAZDA: CX-3
INSERT INTO MARCA_MODELO_VEH VALUES (SEQ_MARCA_MODELO_VEH.NEXTVAL, 3, 5, SYSDATE);
-- KIA: SAIL (competidor directo de CHEVROLET SAIL)
INSERT INTO MARCA_MODELO_VEH VALUES (SEQ_MARCA_MODELO_VEH.NEXTVAL, 4, 2, SYSDATE);
-- TOYOTA: LOGAN (competidor directo de RENAULT LOGAN)
INSERT INTO MARCA_MODELO_VEH VALUES (SEQ_MARCA_MODELO_VEH.NEXTVAL, 5, 3, SYSDATE);

-- Colores de vehiculo
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'BLANCO');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'NEGRO');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'GRIS');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'ROJO');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'AZUL');

-- Estados de vehiculo
INSERT INTO ESTADO_VEHICULO VALUES (SEQ_ESTADO_VEHICULO.NEXTVAL, 'ACTIVO');
INSERT INTO ESTADO_VEHICULO VALUES (SEQ_ESTADO_VEHICULO.NEXTVAL, 'INACTIVO');
INSERT INTO ESTADO_VEHICULO VALUES (SEQ_ESTADO_VEHICULO.NEXTVAL, 'EN_REVISION');

-- Estados de ruta
INSERT INTO ESTADO_RUTA VALUES (SEQ_ESTADO_RUTA.NEXTVAL, 'ACTIVA');
INSERT INTO ESTADO_RUTA VALUES (SEQ_ESTADO_RUTA.NEXTVAL, 'CANCELADA');
INSERT INTO ESTADO_RUTA VALUES (SEQ_ESTADO_RUTA.NEXTVAL, 'COMPLETADA');
INSERT INTO ESTADO_RUTA VALUES (SEQ_ESTADO_RUTA.NEXTVAL, 'EN_CURSO');

-- Estados de solicitud
INSERT INTO ESTADO_SOLICITUD VALUES (SEQ_ESTADO_SOLICITUD.NEXTVAL, 'PENDIENTE');
INSERT INTO ESTADO_SOLICITUD VALUES (SEQ_ESTADO_SOLICITUD.NEXTVAL, 'ACEPTADA');
INSERT INTO ESTADO_SOLICITUD VALUES (SEQ_ESTADO_SOLICITUD.NEXTVAL, 'RECHAZADA');
INSERT INTO ESTADO_SOLICITUD VALUES (SEQ_ESTADO_SOLICITUD.NEXTVAL, 'CANCELADA');

-- Metodos de pago
INSERT INTO METODO_PAGO VALUES (SEQ_METODO_PAGO.NEXTVAL, 'CARTERA_VIRTUAL');
INSERT INTO METODO_PAGO VALUES (SEQ_METODO_PAGO.NEXTVAL, 'EFECTIVO');

-- Estados de cupo en ruta
INSERT INTO ESTADO_CUPO_RUTA VALUES (SEQ_ESTADO_CUPO_RUTA.NEXTVAL, 'RESERVADO');
INSERT INTO ESTADO_CUPO_RUTA VALUES (SEQ_ESTADO_CUPO_RUTA.NEXTVAL, 'CANCELADO');
INSERT INTO ESTADO_CUPO_RUTA VALUES (SEQ_ESTADO_CUPO_RUTA.NEXTVAL, 'COMPLETADO');
x
-- Tipos de transaccion (sin RETIRO)
INSERT INTO TIPO_TRANSACCION VALUES (SEQ_TIPO_TRANSACCION.NEXTVAL, 'RECARGA',    'Recarga de saldo a la cartera');
INSERT INTO TIPO_TRANSACCION VALUES (SEQ_TIPO_TRANSACCION.NEXTVAL, 'PAGO_VIAJE', 'Descuento por pago de cupo');
INSERT INTO TIPO_TRANSACCION VALUES (SEQ_TIPO_TRANSACCION.NEXTVAL, 'REEMBOLSO',  'Devolucion de saldo por cancelacion');

-- =====================================================
-- SECCIÓN 2: INSERT - DATOS DE PRUEBA
-- =====================================================

-- Usuarios de prueba
-- Davison y Jose Luis arrancan con saldo 0 (regla de negocio)
-- Emmanuel (ADMIN) tiene saldo especial de 99999
INSERT INTO USUARIO VALUES (
    '1234567890', 'Davison', 'Jaramillo', 'Gonzalez',
    'davisonjaramillo23251@elpoli.edu.co', '3001234567',
    TO_DATE('1998-05-15', 'YYYY-MM-DD'),
    '$2b$10$l52UO3euHCQUc8m5A4q1xeTyHcBhTb9Oz/crQ.Fivr0jGe4Cdnhqu', 'https://storage/fotos/davison.jpg',
    0, SYSDATE, 1
);
INSERT INTO USUARIO VALUES (
    '0987654321', 'Jose Luis', 'Grajales', 'Cuervo',
    'jose_grajales23251@elpoli.edu.co', '3109876543',
    TO_DATE('2000-09-22', 'YYYY-MM-DD'),
    '$2b$10$kBTm2uw104deC4EYabirvurCH4pdp737BvZrRbVSiAaaTA3AOoq5u', 'https://storage/fotos/jose.jpg',
    0, SYSDATE, 1
);
INSERT INTO USUARIO VALUES (
    '1122334455', 'Emmanuel', 'Echenique', NULL,
    'emmanuelechenique23251@elpoli.edu.co', '3201122334',
    TO_DATE('1995-01-10', 'YYYY-MM-DD'),
    '$2b$10$8mWH/Q7/N.ukF8wkkHO/Uuob7.u8IOZgxUuI5633gawmTCEX8ppYK', 'https://storage/fotos/emmanuel.jpg',
    99999, SYSDATE, 1
);

-- Asignar perfiles a usuarios
-- Se omite CALIFICACION_UPE: Oracle asigna DEFAULT 5.0 automaticamente
INSERT INTO USUARIO_PERFIL (ID_UPE, DOCUMENTO_USU_UPE, ID_PER_UPE, FECHA_ASIGNACION_UPE)
    VALUES (SEQ_USUARIO_PERFIL.NEXTVAL, '1234567890', 1, SYSDATE); -- Davison   -> PASAJERO

INSERT INTO USUARIO_PERFIL (ID_UPE, DOCUMENTO_USU_UPE, ID_PER_UPE, FECHA_ASIGNACION_UPE)
    VALUES (SEQ_USUARIO_PERFIL.NEXTVAL, '1234567890', 2, SYSDATE); -- Davison   -> CONDUCTOR

INSERT INTO USUARIO_PERFIL (ID_UPE, DOCUMENTO_USU_UPE, ID_PER_UPE, FECHA_ASIGNACION_UPE)
    VALUES (SEQ_USUARIO_PERFIL.NEXTVAL, '0987654321', 2, SYSDATE); -- Jose Luis -> CONDUCTOR

INSERT INTO USUARIO_PERFIL (ID_UPE, DOCUMENTO_USU_UPE, ID_PER_UPE, FECHA_ASIGNACION_UPE)
    VALUES (SEQ_USUARIO_PERFIL.NEXTVAL, '1122334455', 3, SYSDATE); -- Emmanuel  -> ADMIN

-- Vehiculo del conductor (Jose Luis)
-- MARCA_MODELO=3 (RENAULT LOGAN) | COLOR=1 BLANCO | ESTADO=1 ACTIVO
INSERT INTO VEHICULO VALUES (
    SEQ_VEHICULO.NEXTVAL, '0987654321', 3, 1, 1,
    'ABC123',
    'https://storage/docs/soat_jose.pdf',
    'https://storage/docs/licencia_jose.pdf',
    'https://storage/docs/tarjeta_jose.pdf',
    'https://storage/fotos/vehiculo_jose.jpg',
    SYSDATE
);

COMMIT;


-- =====================================================
-- SECCIÓN 3: SELECT - CONSULTAS ÚTILES DEL NEGOCIO
-- =====================================================

-- Ver todos los usuarios ordenados por fecha de creacion
SELECT
    DOCUMENTO_USU,
    NOMBRES_USU,
    PRIMER_APELLIDO_USU,
    CORREO_USU,
    SALDO_CARTERA_USU,
    FECHA_CREACION_USU
FROM USUARIO
ORDER BY FECHA_CREACION_USU DESC;

-- Ver todos los perfiles disponibles ordenados por nombre
SELECT
    ID_PER,
    NOMBRE_PER,
    DESCRIPCION_PER
FROM PERFIL
ORDER BY NOMBRE_PER ASC;

-- Ver rutas con sus cupos y precio, ordenadas de mas barato a mas caro
SELECT
    ID_RUT,
    HORA_SALIDA_RUT,
    CUPOS_TOTALES_RUT,
    CUPOS_DISPONIBLES_RUT,
    PRECIO_CUPO_RUT,
    DISTANCIA_KM_RUT
FROM RUTA
WHERE CUPOS_DISPONIBLES_RUT > 0
ORDER BY PRECIO_CUPO_RUT ASC;

-- Contar solicitudes agrupadas por estado
SELECT
    ID_ESO_SOL,
    COUNT(*) AS TOTAL_SOLICITUDES,
    SUM(MONTO_SOL) AS MONTO_TOTAL
FROM SOLICITUD_CUPO
GROUP BY ID_ESO_SOL
ORDER BY TOTAL_SOLICITUDES DESC;

-- Ver historial de viajes de un usuario especifico ordenado por fecha
SELECT
    ID_HIS,
    ROL_VIAJE_HIS,
    FECHA_VIAJE_HIS,
    RUT_ID_HIS
FROM HISTORIAL_VIAJE
WHERE DOCUMENTO_USU_HIS = '1234567890'
ORDER BY FECHA_VIAJE_HIS DESC;

-- Ver calificaciones recibidas por un usuario con su promedio
SELECT
    DOCUMENTO_CALIFICADO_CAL,
    COUNT(*)            AS TOTAL_CALIFICACIONES,
    ROUND(AVG(PUNTAJE_CAL), 1) AS PROMEDIO,
    MIN(PUNTAJE_CAL)    AS PUNTAJE_MINIMO,
    MAX(PUNTAJE_CAL)    AS PUNTAJE_MAXIMO
FROM CALIFICACION
WHERE DOCUMENTO_CALIFICADO_CAL = '0987654321'
GROUP BY DOCUMENTO_CALIFICADO_CAL;

-- Ver transacciones de cartera de un usuario ordenadas por fecha
SELECT
    ID_TRA,
    ID_TTR_TRA,
    MONTO_TRA,
    SALDO_RESULTANTE_TRA,
    FECHA_REALIZACION_TRA
FROM TRANSACCIONES_CARTERA
WHERE DOCUMENTO_USU_TRA = '1234567890'
ORDER BY FECHA_REALIZACION_TRA DESC;


-- =====================================================
-- SECCIÓN 4: UPDATE - ACTUALIZACIONES COMUNES
-- =====================================================

-- Actualizar foto de perfil de un usuario
UPDATE USUARIO
SET FOTO_URL_USU = 'https://storage/fotos/davison_nuevo.jpg'
WHERE DOCUMENTO_USU = '1234567890';

-- Actualizar saldo de cartera al hacer una recarga
UPDATE USUARIO
SET SALDO_CARTERA_USU = SALDO_CARTERA_USU + 30000
WHERE DOCUMENTO_USU = '1234567890';

-- Cambiar estado de una ruta a EN_CURSO
UPDATE RUTA
SET ID_EST_RUT = (SELECT ID_ERU FROM ESTADO_RUTA WHERE NOMBRE_ERU = 'EN_CURSO'),
    FECHA_ACTUALIZACION_RUT = SYSDATE
WHERE ID_RUT = 1;

-- Aceptar una solicitud de cupo
UPDATE SOLICITUD_CUPO
SET ID_ESO_SOL = (SELECT ID_ESO FROM ESTADO_SOLICITUD WHERE NOMBRE_ESO = 'ACEPTADA')
WHERE ID_SOL = 1;

-- Actualizar cupos disponibles al aceptar un pasajero
UPDATE RUTA
SET CUPOS_DISPONIBLES_RUT = CUPOS_DISPONIBLES_RUT - 1,
    FECHA_ACTUALIZACION_RUT = SYSDATE
WHERE ID_RUT = 1;

-- Suspender un usuario
UPDATE USUARIO
SET ID_EST_USU = (SELECT ID_EUS FROM ESTADO_USUARIO WHERE NOMBRE_EUS = 'SUSPENDIDO')
WHERE DOCUMENTO_USU = '1234567890';

COMMIT;


-- =====================================================
-- SECCIÓN 5: DELETE - ELIMINACIONES
-- =====================================================

-- Cancelar una solicitud (cambio de estado, no se borra el registro)
UPDATE SOLICITUD_CUPO
SET ID_ESO_SOL = (SELECT ID_ESO FROM ESTADO_SOLICITUD WHERE NOMBRE_ESO = 'CANCELADA')
WHERE ID_SOL = 1;

-- Eliminar códigos de verificación ya usados y expirados (limpieza periódica)
DELETE FROM VERIFICACION_CORREO
WHERE USADO_VER = 'S'
AND FECHA_EXPIRACION_VER < SYSDATE;

-- Eliminar un vehículo inactivo sin rutas asociadas
DELETE FROM VEHICULO
WHERE ID_EST_VEH = (SELECT ID_EVE FROM ESTADO_VEHICULO WHERE NOMBRE_EVE = 'INACTIVO')
AND ID_VEH NOT IN (SELECT DISTINCT ID_VEH_RUT FROM RUTA);

COMMIT;

prompt =====================================================
prompt Modulo 4 ejecutado: DML - VamonosPues
prompt =====================================================