-- =====================================================
-- SECCIÓN 1: INSERT - ENTIDADES FUERTES (datos base)
-- =====================================================

-- Estados de usuario
INSERT INTO ESTADO_USUARIO VALUES (SEQ_ESTADO_USUARIO.NEXTVAL, 'ACTIVO',     'Usuario activo en el sistema');
INSERT INTO ESTADO_USUARIO VALUES (SEQ_ESTADO_USUARIO.NEXTVAL, 'INACTIVO',   'Usuario desactivado');
INSERT INTO ESTADO_USUARIO VALUES (SEQ_ESTADO_USUARIO.NEXTVAL, 'SUSPENDIDO', 'Usuario suspendido por incumplimiento');
INSERT INTO ESTADO_USUARIO VALUES (SEQ_ESTADO_USUARIO.NEXTVAL, 'PENDIENTE',  'Cuenta pendiente de verificacion');

-- Perfiles
INSERT INTO PERFIL VALUES (SEQ_PERFIL.NEXTVAL, 'PASAJERO',  'Usuario que solicita cupos en rutas', SYSDATE);
INSERT INTO PERFIL VALUES (SEQ_PERFIL.NEXTVAL, 'CONDUCTOR', 'Usuario que publica rutas y conduce', SYSDATE);
INSERT INTO PERFIL VALUES (SEQ_PERFIL.NEXTVAL, 'ADMIN',     'Administrador del sistema',           SYSDATE);

-- Marcas de vehiculo
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'CHEVROLET');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'RENAULT');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'MAZDA');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'KIA');
INSERT INTO MARCA_VEHICULO VALUES (SEQ_MARCA_VEHICULO.NEXTVAL, 'TOYOTA');

-- Modelos de vehiculo
INSERT INTO MODELO_VEHICULO VALUES (SEQ_MODELO_VEHICULO.NEXTVAL, 'SPARK',   2020);
INSERT INTO MODELO_VEHICULO VALUES (SEQ_MODELO_VEHICULO.NEXTVAL, 'SAIL',    2021);
INSERT INTO MODELO_VEHICULO VALUES (SEQ_MODELO_VEHICULO.NEXTVAL, 'LOGAN',   2019);
INSERT INTO MODELO_VEHICULO VALUES (SEQ_MODELO_VEHICULO.NEXTVAL, 'SANDERO', 2022);
INSERT INTO MODELO_VEHICULO VALUES (SEQ_MODELO_VEHICULO.NEXTVAL, 'CX-3',    2020);

-- Colores de vehiculo
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'BLANCO');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'NEGRO');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'GRIS');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'ROJO');
INSERT INTO COLOR_VEHICULO VALUES (SEQ_COLOR_VEHICULO.NEXTVAL, 'AZUL');

-- Estados de vehiculo
INSERT INTO ESTADO_VEHICULO VALUES (SEQ_ESTADO_VEHICULO.NEXTVAL, 'ACTIVO');
INSERT INTO ESTADO_VEHICULO VALUES (SEQ_ESTADO_VEHICULO.NEXTVAL, 'INACTIVO');
INSERT INTO ESTADO_VEHICULO VALUES (SEQ_ESTADO_VEHICULO.NEXTVAL, 'EN_REVISION');

-- Estados de ruta
INSERT INTO ESTADO_RUTA VALUES (SEQ_ESTADO_RUTA.NEXTVAL, 'ACTIVA');
INSERT INTO ESTADO_RUTA VALUES (SEQ_ESTADO_RUTA.NEXTVAL, 'CANCELADA');
INSERT INTO ESTADO_RUTA VALUES (SEQ_ESTADO_RUTA.NEXTVAL, 'COMPLETADA');
INSERT INTO ESTADO_RUTA VALUES (SEQ_ESTADO_RUTA.NEXTVAL, 'EN_CURSO');

-- Estados de solicitud
INSERT INTO ESTADO_SOLICITUD VALUES (SEQ_ESTADO_SOLICITUD.NEXTVAL, 'PENDIENTE');
INSERT INTO ESTADO_SOLICITUD VALUES (SEQ_ESTADO_SOLICITUD.NEXTVAL, 'ACEPTADA');
INSERT INTO ESTADO_SOLICITUD VALUES (SEQ_ESTADO_SOLICITUD.NEXTVAL, 'RECHAZADA');
INSERT INTO ESTADO_SOLICITUD VALUES (SEQ_ESTADO_SOLICITUD.NEXTVAL, 'CANCELADA');

-- Metodos de pago
INSERT INTO METODO_PAGO VALUES (SEQ_METODO_PAGO.NEXTVAL, 'CARTERA_VIRTUAL');
INSERT INTO METODO_PAGO VALUES (SEQ_METODO_PAGO.NEXTVAL, 'EFECTIVO');

-- Estados de cupo en ruta
INSERT INTO ESTADO_CUPO_RUTA VALUES (SEQ_ESTADO_CUPO_RUTA.NEXTVAL, 'RESERVADO');
INSERT INTO ESTADO_CUPO_RUTA VALUES (SEQ_ESTADO_CUPO_RUTA.NEXTVAL, 'CANCELADO');
INSERT INTO ESTADO_CUPO_RUTA VALUES (SEQ_ESTADO_CUPO_RUTA.NEXTVAL, 'COMPLETADO');

-- Tipos de transaccion (sin RETIRO)
INSERT INTO TIPO_TRANSACCION VALUES (SEQ_TIPO_TRANSACCION.NEXTVAL, 'RECARGA',    'Recarga de saldo a la cartera');
INSERT INTO TIPO_TRANSACCION VALUES (SEQ_TIPO_TRANSACCION.NEXTVAL, 'PAGO_VIAJE', 'Descuento por pago de cupo');
INSERT INTO TIPO_TRANSACCION VALUES (SEQ_TIPO_TRANSACCION.NEXTVAL, 'REEMBOLSO',  'Devolucion de saldo por cancelacion');

-- Menu principal
INSERT INTO MENU VALUES (SEQ_MENU.NEXTVAL, '/dashboard',      'Inicio',         NULL, 1);
INSERT INTO MENU VALUES (SEQ_MENU.NEXTVAL, '/rutas',          'Rutas',          NULL, 2);
INSERT INTO MENU VALUES (SEQ_MENU.NEXTVAL, '/rutas/buscar',   'Buscar Ruta',    2,    1);
INSERT INTO MENU VALUES (SEQ_MENU.NEXTVAL, '/rutas/publicar', 'Publicar Ruta',  2,    2);
INSERT INTO MENU VALUES (SEQ_MENU.NEXTVAL, '/perfil',         'Mi Perfil',      NULL, 3);
INSERT INTO MENU VALUES (SEQ_MENU.NEXTVAL, '/historial',      'Historial',      NULL, 4);
INSERT INTO MENU VALUES (SEQ_MENU.NEXTVAL, '/admin',          'Administracion', NULL, 5);
INSERT INTO MENU VALUES (SEQ_MENU.NEXTVAL, '/solicitudes',    'Solicitudes',    NULL, 6);
INSERT INTO MENU VALUES (SEQ_MENU.NEXTVAL, '/vehiculos',      'Mis Vehiculos',  NULL, 7);

-- Permisos ADMIN (perfil 3) - acceso total a todo
INSERT INTO MENU_PERFIL VALUES (1, 3, 'S','S','S','S');
INSERT INTO MENU_PERFIL VALUES (2, 3, 'S','S','S','S');
INSERT INTO MENU_PERFIL VALUES (3, 3, 'S','S','S','S');
INSERT INTO MENU_PERFIL VALUES (4, 3, 'S','S','S','S');
INSERT INTO MENU_PERFIL VALUES (5, 3, 'S','S','S','S');
INSERT INTO MENU_PERFIL VALUES (6, 3, 'S','S','S','S');
INSERT INTO MENU_PERFIL VALUES (7, 3, 'S','S','S','S');
INSERT INTO MENU_PERFIL VALUES (8, 3, 'S','S','S','S');
INSERT INTO MENU_PERFIL VALUES (9, 3, 'S','S','S','S');

-- Permisos PASAJERO (perfil 1)
INSERT INTO MENU_PERFIL VALUES (1, 1, 'N','N','N','S'); -- Ver inicio
INSERT INTO MENU_PERFIL VALUES (2, 1, 'N','N','N','S'); -- Ver rutas
INSERT INTO MENU_PERFIL VALUES (3, 1, 'S','N','N','S'); -- Buscar ruta (puede solicitar)
INSERT INTO MENU_PERFIL VALUES (5, 1, 'N','S','N','S'); -- Mi perfil
INSERT INTO MENU_PERFIL VALUES (6, 1, 'N','N','N','S'); -- Historial
INSERT INTO MENU_PERFIL VALUES (8, 1, 'S','S','N','S'); -- Solicitudes

-- Permisos CONDUCTOR (perfil 2)
INSERT INTO MENU_PERFIL VALUES (1, 2, 'N','N','N','S'); -- Ver inicio
INSERT INTO MENU_PERFIL VALUES (2, 2, 'N','N','N','S'); -- Ver rutas
INSERT INTO MENU_PERFIL VALUES (4, 2, 'S','S','S','S'); -- Publicar ruta (CRUD completo)
INSERT INTO MENU_PERFIL VALUES (5, 2, 'N','S','N','S'); -- Mi perfil
INSERT INTO MENU_PERFIL VALUES (6, 2, 'N','N','N','S'); -- Historial
INSERT INTO MENU_PERFIL VALUES (8, 2, 'N','S','N','S'); -- Solicitudes (aceptar/rechazar)
INSERT INTO MENU_PERFIL VALUES (9, 2, 'S','S','S','S'); -- Vehiculos

COMMIT;


-- =====================================================
-- SECCIÓN 2: INSERT - DATOS DE PRUEBA
-- =====================================================

-- Usuarios de prueba
-- Davison y Jose Luis arrancan con saldo 0 (regla de negocio)
-- Emmanuel (ADMIN) tiene saldo especial de 99999
INSERT INTO USUARIO VALUES (
    '1234567890', 'Davison', 'Jaramillo', 'Gonzalez',
    'davisonjaramillo23251@elpoli.edu.co', '3001234567',
    TO_DATE('1998-05-15', 'YYYY-MM-DD'),
    '$2b$10$l52UO3euHCQUc8m5A4q1xeTyHcBhTb9Oz/crQ.Fivr0jGe4Cdnhqu', 'https://storage/fotos/davison.jpg',
    0, SYSDATE, 1
);
INSERT INTO USUARIO VALUES (
    '0987654321', 'Jose Luis', 'Grajales', 'Cuervo',
    'jose_grajales23251@elpoli.edu.co', '3109876543',
    TO_DATE('2000-09-22', 'YYYY-MM-DD'),
    '$2b$10$kBTm2uw104deC4EYabirvurCH4pdp737BvZrRbVSiAaaTA3AOoq5u', 'https://storage/fotos/jose.jpg',
    0, SYSDATE, 1
);
INSERT INTO USUARIO VALUES (
    '1122334455', 'Emmanuel', 'Echenique', NULL,
    'emmanuelechenique23251@elpoli.edu.co', '3201122334',
    TO_DATE('1995-01-10', 'YYYY-MM-DD'),
    '$2b$10$8mWH/Q7/N.ukF8wkkHO/Uuob7.u8IOZgxUuI5633gawmTCEX8ppYK', 'https://storage/fotos/emmanuel.jpg',
    99999, SYSDATE, 1
);

-- Asignar perfiles a usuarios
-- Se omite CALIFICACION_UPE: Oracle asigna DEFAULT 5.0 automaticamente
INSERT INTO USUARIO_PERFIL (ID_UPE, DOCUMENTO_USU_UPE, ID_PER_UPE, FECHA_ASIGNACION_UPE)
    VALUES (SEQ_USUARIO_PERFIL.NEXTVAL, '1234567890', 1, SYSDATE); -- Davison   -> PASAJERO

INSERT INTO USUARIO_PERFIL (ID_UPE, DOCUMENTO_USU_UPE, ID_PER_UPE, FECHA_ASIGNACION_UPE)
    VALUES (SEQ_USUARIO_PERFIL.NEXTVAL, '0987654321', 2, SYSDATE); -- Jose Luis -> CONDUCTOR

INSERT INTO USUARIO_PERFIL (ID_UPE, DOCUMENTO_USU_UPE, ID_PER_UPE, FECHA_ASIGNACION_UPE)
    VALUES (SEQ_USUARIO_PERFIL.NEXTVAL, '1122334455', 3, SYSDATE); -- Emmanuel  -> ADMIN

-- Vehiculo del conductor (Jose Luis)
-- MARCA=1 CHEVROLET | MODELO=3 LOGAN | COLOR=1 BLANCO | ESTADO=1 ACTIVO
INSERT INTO VEHICULO VALUES (
    SEQ_VEHICULO.NEXTVAL, '0987654321', 1, 3, 1, 1,
    'ABC123',
    'https://storage/docs/soat_jose.pdf',
    'https://storage/docs/licencia_jose.pdf',
    'https://storage/docs/tarjeta_jose.pdf',
    'https://storage/fotos/vehiculo_jose.jpg',
    SYSDATE
);

COMMIT;

prompt =====================================================
prompt Modulo 4 ejecutado: DML (solo INSERTs) - VamonosPues
prompt =====================================================