-- =====================================================
-- Datos de prueba para flujo conductor/pasajero
-- =====================================================
-- Este script usa los usuarios de prueba ya cargados en el script 4.
-- Conductor: 0987654321
-- Pasajero: 1234567890
-- Admin: 1122334455

-- 1) Insertar rutas de conductor
INSERT INTO RUTA (
    ID_RUT,
    ID_UPE_RUT,
    ID_VEH_RUT,
    ID_EST_RUT,
    LATITUD_ORIGEN_RUT,
    LONGITUD_ORIGEN_RUT,
    LATITUD_DESTINO_RUT,
    LONGITUD_DESTINO_RUT,
    HORA_SALIDA_RUT,
    CUPOS_TOTALES_RUT,
    CUPOS_DISPONIBLES_RUT,
    PRECIO_CUPO_RUT,
    DISTANCIA_KM_RUT,
    FECHA_ACTUALIZACION_RUT
) VALUES (
    SEQ_RUTA.NEXTVAL,
    (SELECT ID_UPE FROM USUARIO_PERFIL WHERE DOCUMENTO_USU_UPE = '0987654321' AND ID_PER_UPE = 2),
    (SELECT ID_VEH FROM VEHICULO WHERE DOCUMENTO_USU_VEH = '0987654321' AND PLACA_VEH = 'ABC123'),
    (SELECT ID_ERU FROM ESTADO_RUTA WHERE NOMBRE_ERU = 'ACTIVA'),
    6.251839, -75.581228,
    6.197458, -75.567108,
    TO_DATE('2026-05-25 07:15:00', 'YYYY-MM-DD HH24:MI:SS'),
    3,
    3,
    8500,
    12.3,
    SYSDATE
);

INSERT INTO RUTA (
    ID_RUT,
    ID_UPE_RUT,
    ID_VEH_RUT,
    ID_EST_RUT,
    LATITUD_ORIGEN_RUT,
    LONGITUD_ORIGEN_RUT,
    LATITUD_DESTINO_RUT,
    LONGITUD_DESTINO_RUT,
    HORA_SALIDA_RUT,
    CUPOS_TOTALES_RUT,
    CUPOS_DISPONIBLES_RUT,
    PRECIO_CUPO_RUT,
    DISTANCIA_KM_RUT,
    FECHA_ACTUALIZACION_RUT
) VALUES (
    SEQ_RUTA.NEXTVAL,
    (SELECT ID_UPE FROM USUARIO_PERFIL WHERE DOCUMENTO_USU_UPE = '0987654321' AND ID_PER_UPE = 2),
    (SELECT ID_VEH FROM VEHICULO WHERE DOCUMENTO_USU_VEH = '0987654321' AND PLACA_VEH = 'ABC123'),
    (SELECT ID_ERU FROM ESTADO_RUTA WHERE NOMBRE_ERU = 'ACTIVA'),
    6.242200, -75.590780,
    6.181200, -75.570000,
    TO_DATE('2026-05-25 08:45:00', 'YYYY-MM-DD HH24:MI:SS'),
    2,
    2,
    9500,
    8.7,
    SYSDATE
);

COMMIT;

-- 2) Insertar solicitudes de cupo de pasajeros
INSERT INTO SOLICITUD_CUPO (
    ID_SOL,
    ID_UPE_SOL,
    ID_RUT_SOL,
    ID_ESO_SOL,
    ID_MPA_SOL,
    MONTO_SOL,
    FECHA_CREACION_SOL
)
SELECT
    SEQ_SOLICITUD_CUPO.NEXTVAL,
    (SELECT ID_UPE FROM USUARIO_PERFIL WHERE DOCUMENTO_USU_UPE = '1234567890' AND ID_PER_UPE = 1),
    (SELECT ID_RUT FROM RUTA WHERE HORA_SALIDA_RUT = TO_DATE('2026-05-25 07:15:00', 'YYYY-MM-DD HH24:MI:SS') AND ROWNUM = 1),
    (SELECT ID_ESO FROM ESTADO_SOLICITUD WHERE NOMBRE_ESO = 'PENDIENTE'),
    (SELECT ID_MPA FROM METODO_PAGO WHERE NOMBRE_MPA = 'CARTERA_VIRTUAL'),
    8500,
    SYSDATE
FROM DUAL;

INSERT INTO SOLICITUD_CUPO (
    ID_SOL,
    ID_UPE_SOL,
    ID_RUT_SOL,
    ID_ESO_SOL,
    ID_MPA_SOL,
    MONTO_SOL,
    FECHA_CREACION_SOL
)
SELECT
    SEQ_SOLICITUD_CUPO.NEXTVAL,
    (SELECT ID_UPE FROM USUARIO_PERFIL WHERE DOCUMENTO_USU_UPE = '1234567890' AND ID_PER_UPE = 1),
    (SELECT ID_RUT FROM RUTA WHERE HORA_SALIDA_RUT = TO_DATE('2026-05-25 08:45:00', 'YYYY-MM-DD HH24:MI:SS') AND ROWNUM = 1),
    (SELECT ID_ESO FROM ESTADO_SOLICITUD WHERE NOMBRE_ESO = 'ACEPTADA'),
    (SELECT ID_MPA FROM METODO_PAGO WHERE NOMBRE_MPA = 'EFECTIVO'),
    9500,
    SYSDATE
FROM DUAL;

COMMIT;

-- 3) Actualizar cupos y confirmar solicitud aceptada para la segunda ruta
UPDATE RUTA
SET CUPOS_DISPONIBLES_RUT = CUPOS_DISPONIBLES_RUT - 1,
    FECHA_ACTUALIZACION_RUT = SYSDATE
WHERE ID_RUT = (
    SELECT ID_RUT FROM RUTA
    WHERE HORA_SALIDA_RUT = TO_DATE('2026-05-25 08:45:00', 'YYYY-MM-DD HH24:MI:SS')
    AND ROWNUM = 1
);

COMMIT;

-- 4) Registrar la reserva aprobada en CUPO_RUTA
INSERT INTO CUPO_RUTA (
    ID_SOL_CRU,
    ID_RUT_CRU,
    ID_ECU_CRU,
    FECHA_APROBACION_CRU
)
SELECT
    s.ID_SOL,
    s.ID_RUT_SOL,
    (SELECT ID_ECU FROM ESTADO_CUPO_RUTA WHERE NOMBRE_ECU = 'RESERVADO'),
    SYSDATE
FROM SOLICITUD_CUPO s
WHERE s.ID_ESO_SOL = (SELECT ID_ESO FROM ESTADO_SOLICITUD WHERE NOMBRE_ESO = 'ACEPTADA')
  AND s.ID_RUT_SOL = (
        SELECT ID_RUT FROM RUTA
        WHERE HORA_SALIDA_RUT = TO_DATE('2026-05-25 08:45:00', 'YYYY-MM-DD HH24:MI:SS')
        AND ROWNUM = 1
    )
  AND ROWNUM = 1;

COMMIT;

-- 5) Crear un historial de viaje completado para el pasajero en la segunda ruta
INSERT INTO HISTORIAL_VIAJE (
    ID_HIS,
    SOL_ID_HIS,
    RUT_ID_HIS,
    DOCUMENTO_USU_HIS,
    ROL_VIAJE_HIS,
    FECHA_VIAJE_HIS
)
SELECT
    SEQ_HISTORIAL_VIAJE.NEXTVAL,
    s.ID_SOL,
    s.ID_RUT_SOL,
    '1234567890',
    'PASAJERO',
    TO_DATE('2026-05-25 09:55:00', 'YYYY-MM-DD HH24:MI:SS')
FROM SOLICITUD_CUPO s
WHERE s.ID_ESO_SOL = (SELECT ID_ESO FROM ESTADO_SOLICITUD WHERE NOMBRE_ESO = 'ACEPTADA')
  AND s.ID_RUT_SOL = (
        SELECT ID_RUT FROM RUTA
        WHERE HORA_SALIDA_RUT = TO_DATE('2026-05-25 08:45:00', 'YYYY-MM-DD HH24:MI:SS')
        AND ROWNUM = 1
    )
  AND ROWNUM = 1;

COMMIT;

-- 6) Consultas para verificar los datos de prueba
SELECT * FROM RUTA WHERE ID_UPE_RUT = (
    SELECT ID_UPE FROM USUARIO_PERFIL WHERE DOCUMENTO_USU_UPE = '0987654321' AND ID_PER_UPE = 2
);

SELECT * FROM SOLICITUD_CUPO WHERE ID_UPE_SOL = (
    SELECT ID_UPE FROM USUARIO_PERFIL WHERE DOCUMENTO_USU_UPE = '1234567890' AND ID_PER_UPE = 1
);

SELECT * FROM CUPO_RUTA;
SELECT * FROM HISTORIAL_VIAJE;
