-- ===================================================================
-- Script para crear tabla RECUPERACION_CONTRASENA
-- Sistema: Vamos Pues
-- ===================================================================
DROP TABLE RECUPERACION_CONTRASENA CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_RECUPERACION_CONTRASENA;

-- Crear tabla

CREATE TABLE RECUPERACION_CONTRASENA (
    ID_REC NUMBER PRIMARY KEY,
    DOCUMENTO_USU_REC VARCHAR2(15) NOT NULL,
    TOKEN_REC VARCHAR2(500) NOT NULL,
    FECHA_EXPIRACION_REC DATE NOT NULL,
    USADO_REC CHAR(1) DEFAULT 'N' CHECK (USADO_REC IN ('S', 'N')),
    FECHA_CREACION_REC DATE DEFAULT SYSDATE,
    CONSTRAINT FK_REC_USU FOREIGN KEY (DOCUMENTO_USU_REC) 
        REFERENCES USUARIO(DOCUMENTO_USU) ON DELETE CASCADE
);

-- Crear secuencia para la tabla
CREATE SEQUENCE SEQ_RECUPERACION_CONTRASENA START WITH 1 INCREMENT BY 1;

-- Crear índices para optimizar búsquedas
CREATE INDEX IDX_REC_TOKEN ON RECUPERACION_CONTRASENA(TOKEN_REC);

-- Commit
COMMIT;
